### ISSUE TITLE
建议增加上下文支持

### ISSUE THREAD

**Issue by haydonchou** [lxerxa/actionview#101]
目前很多场景下，还是走的统一ip和端口，如果不支持配置上下文，将大大受限啊，希望能够支持增加上下文。

**Comment by lxerxa** [comment]
可以支持的，不过需要前端重新打包。

**Comment by haydonchou** [comment]
@lxerxa 具体怎么操作呢，建议加在使用手册中。

**Comment by lxerxa** [comment]
下个版本支持。

**Comment by lxerxa** [comment]
新版本(v.1.11.0)已支持，请关注。

**Comment by haydonchou** [comment]
@lxerxa  assets 目录好像处理有问题，绝对地址未增加context path，导致登录页的logo图片加载不出来。

**Comment by haydonchou** [comment]
@lxerxa  assets 目录好像处理有问题，绝对地址未增加context path，导致登录页的logo图片加载不出来。

**Comment by lxerxa** [comment]
了解，尽快发布新版本。

**Comment by lxerxa** [comment]
@haydonchou v1.11.1已发布，修复了该问题。

**Comment by haydonchou** [comment]
@lxerxa 您好！测试了几天，发现了一个新问题，登录后，为什么刷新会是404？我从github下载包，按照安装手册重新安装的也存在这个问题，但是我看actionview的演示网站登录后刷新并不会404.不知道您重新安装会不会重现问题。

**Comment by lxerxa** [comment]
谢谢你的测试，安装方式是？

**Comment by haydonchou** [comment]
@lxerxa  https://github.com/lxerxa/actionview/wiki/CentOS-Installation(Nginx)  
使用的source.zip

**Comment by lxerxa** [comment]
应该是加context path的原因, nginx的配置文件能发下吗？

**Comment by haydonchou** [comment]
@lxerxa nginx的配置就是文档中的，没有修改过。

**Comment by haydonchou** [comment]
@lxerxa nginx的配置就是文档中的，没有修改过。

**Comment by lxerxa** [comment]
了解，可能是webpack应该少了一个base的配置项，疑惑Demo为什么没问题，Apache服务器的原因？等新版本发布后您再帮确认一下吧。

**Comment by lxerxa** [comment]
@haydonchou 参照新的nginx配置文件修改即可。https://github.com/lxerxa/actionview/wiki/CentOS-Installation(Nginx)

**Comment by haydonchou** [comment]
@lxerxa 测试了，可以正常刷新了。此issue可以关闭了。
