### ISSUE TITLE
看板创建问题之后消失，要如何正确操作

### ISSUE THREAD

**Issue by Yingkb** [lxerxa/actionview#103]
看板创建问题之后消失，要如何正确操作

**Comment by lxerxa** [comment]
没明白，可截图或录一段视频。

**Comment by lxerxa** [comment]
如果看板的类型是kanban, 设置了“解决版本”的问题是不能显示出来的。

**Comment by Yingkb** [comment]
我就是创建新的项目，然后再创建"看板"，再创建"问题"一开始显示在 "开始"那个初始面板，然后我手动刷新页面的时候，看板上就没有这个"问题"了

**Comment by Yingkb** [comment]
![image](https://user-images.githubusercontent.com/59404867/81491053-01355200-92bc-11ea-8131-d2c685927b91.png)

**Comment by Yingkb** [comment]
![image](https://user-images.githubusercontent.com/59404867/81491058-0befe700-92bc-11ea-8d05-6f59a9d3a398.png)

**Comment by lxerxa** [comment]
问题的详细页面呢？是不是设置了解决版本？

**Comment by Yingkb** [comment]
明白了 谢谢
