### ISSUE TITLE
Kanban Scrum  board should have ability to show cards based on assignee

### ISSUE THREAD

**Issue by azhershaikh** [lxerxa/actionview#105]
Action view must support feature for Kanban Scrum board bility to show cards based on assignee.
Currently board has filters on top.
It would be nice if we show the board separated by each user. 
Please find attached file for example.
![AsssigneeBoard](https://user-images.githubusercontent.com/27428581/81652576-9584ed80-9451-11ea-89db-42d5ef7c6074.PNG)

**Comment by lxerxa** [comment]
Thanks for your advice, will have time to optimize the function in the future.
