### ISSUE TITLE
希望布局可以紧凑一点

### ISSUE THREAD

**Issue by kevinrsa** [lxerxa/actionview#107]

**Comment by lxerxa** [comment]
能给出一些更具体的建议吗？因为我对前端的布局不专业。

**Comment by kevinrsa** [comment]
我也不是专业人员:-D

- 整体的布局，个人习惯类似禅道的布局
- gantt图个人比较喜欢[gantt-elastic](https://github.com/neuronetio/gantt-elastic)

**Comment by lxerxa** [comment]
谢谢，将来有时间慢慢优化吧。
