### ISSUE TITLE
项目进度和开始时间问题

### ISSUE THREAD

**Issue by gjwhw** [lxerxa/actionview#109]
我的actionview在升级到最新版本后，在字段页面没有期望开始时间和进度，所以在甘特图中无法显示，怎么处理？

**Comment by lxerxa** [comment]
在全局字段配置里手动增加以下两个字段: expect_start_time（期望开始时间）和 progress(进度)，然后再关联到问题页面就可以了。

**Comment by lxerxa** [comment]
字段类型可参考演示站点的配置。
