### ISSUE TITLE
过滤器设置条件关联用户为当前用户无法过滤到卡片

### ISSUE THREAD

**Issue by zjkyz8** [lxerxa/actionview#111]
http://www.actionview.cn:8080/ 中 以红中登录, 创建了一个看板过滤器hahahah, 条件为关联用户包含当前用户,  卡片 http://www.actionview.cn:8080/actionview/project/demo/issue?no=730 关联用户添加了红中, 使用过滤器后所有卡片均不显示.

**Comment by lxerxa** [comment]
谢谢您的问题，已修复。

**Comment by zjkyz8** [comment]
请问这个问题会在什么时候发新版本呢？

**Comment by lxerxa** [comment]
如果是自己安装的，直接更新最新代码就可以了。
