### ISSUE TITLE
作者可以考虑加入截图上传图片吗

### ISSUE THREAD

**Issue by maszy** [lxerxa/actionview#112]
测试人员发现BUG直接截图，现在需要单独保存下截图做图片上传，能优化这步操作，直接截图后上传吗？

**Comment by lxerxa** [comment]
现在问题的描述里是支持上传截图的。
![image](https://user-images.githubusercontent.com/5182909/83641651-655be500-a5e0-11ea-97f7-3d5e0d116b2a.png)
