### ISSUE TITLE
没有创建问题的按钮

### ISSUE THREAD

**Issue by ktownag** [lxerxa/actionview#113]
![image](https://user-images.githubusercontent.com/42381296/84360506-3b578380-abdb-11ea-8223-c4e340d0e5db.png)
本人小白，刚搭建好，请问是什么问题？

**Comment by ktownag** [comment]
![image](https://user-images.githubusercontent.com/42381296/84360667-82457900-abdb-11ea-8df6-b52bcc9ee45f.png)
官网的demo有这个按钮。我建的就没有:(

**Comment by lxerxa** [comment]
该用户所属角色需要有创建问题的权限。

**Comment by ktownag** [comment]
谢谢回复，请问如何为用户赋予角色？

**Comment by ktownag** [comment]
已搞懂：项目——成员，在相应角色中添加用户。

**Comment by ktownag** [comment]
问题关闭。如需翻译为其他语言，我愿意协助，会用CAT工具
