### ISSUE TITLE
将版本从1.8.5升级到目前最新遇到问题

### ISSUE THREAD

**Issue by miladuojx** [lxerxa/actionview#116]
目前版本是1.8.5 想升级到最新1.11.2
在升级的过程中，会报如下的信息：
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

我理解是可以忽略的，继续升级完成后。页面打开是白板的，没有登陆信息。也没有看见有啥有用的错误信息，查看nginx的日志，会有HTTP/1.1" 304的错误日志。
求解题思路。谢谢！

**Comment by lxerxa** [comment]
v1.11.0 开始支持context path，导致以前版本升级无法访问，需要修改nginx的配置文件，

```
server {
    listen 80;
    listen [::]:80;

    root /var/www/actionview/public;

    server_name localhost;

    client_max_body_size 100M;

    location ^~ /actionview/api {
        index index.html index.htm index.php;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ^~ /actionview {
        add_header Cache-Control 'no-cache, must-revalidate, max-age=0';
        alias /var/www/actionview/public/;
        index index.html index.htm index.php;
        try_files $uri $uri/ /index.html$is_args$args;
    }

    location / {
       add_header Cache-Control 'no-cache, must-revalidate, max-age=0';
       index index.html index.htm index.php;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ \.php {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        try_files $uri =404;
    }
}
```

修改后 访问路径需要加上 actionview, 例如： http://xx.xx.xx.xx/actionview/

**Comment by miladuojx** [comment]
谢谢解答！问题已经得到解决。

**Comment by miladuojx** [comment]
> v1.11.0 开始支持context path，导致以前版本升级无法访问，需要修改nginx的配置文件，
> 
> ```
> server {
>     listen 80;
>     listen [::]:80;
> 
>     root /var/www/actionview/public;
> 
>     server_name localhost;
> 
>     client_max_body_size 100M;
> 
>     location ^~ /actionview/api {
>         index index.html index.htm index.php;
>         try_files $uri $uri/ /index.php$is_args$args;
>     }
> 
>     location ^~ /actionview {
>         add_header Cache-Control 'no-cache, must-revalidate, max-age=0';
>         alias /var/www/actionview/public/;
>         index index.html index.htm index.php;
>         try_files $uri $uri/ /index.html$is_args$args;
>     }
> 
>     location / {
>        add_header Cache-Control 'no-cache, must-revalidate, max-age=0';
>        index index.html index.htm index.php;
>     }
> 
>     location ~ /\.ht {
>         deny all;
>     }
> 
>     location ~ \.php {
>         fastcgi_pass   127.0.0.1:9000;
>         fastcgi_index  index.php;
>         include        fastcgi_params;
>         fastcgi_split_path_info ^(.+\.php)(/.+)$;
>         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>         fastcgi_param SCRIPT_NAME $fastcgi_script_name;
>         try_files $uri =404;
>     }
> }
> ```
> 
> 修改后 访问路径需要加上 actionview, 例如： http://xx.xx.xx.xx/actionview/

谢谢解答！问题已经得到解决。
