### ISSUE TITLE
将版本从1.8.5升级到目前最新遇到问题(图片不显示的问题)

### ISSUE THREAD

**Issue by miladuojx** [lxerxa/actionview#117]
由版本是1.8.5 升级到最新1.11.2
其它都是正常的，现在发现部分看板里面的图片无法正常显示，也没有报错。
而且这个现象只是部分图片无法显示，有些老的图片也能正常显示。
![image](https://user-images.githubusercontent.com/45323739/84615460-a8308d80-aefb-11ea-8373-a4505850813a.png)

**Comment by lxerxa** [comment]
描述中的截图链接会有问题，手动改下那个描述链接：在/api/xxxx 前边加上actionview，如： /actionview/api/xxx

**Comment by miladuojx** [comment]
> 描述中的截图链接会有问题，手动改下那个描述链接：在/api/xxxx 前边加上actionview，如： /actionview/api/xxx

的确是这样的，问题我现在已经解决了。
我在nginx里面加一个跳转的配置，问题已修复。
location ^~ /api/ {
        rewrite ^/api/(.*)$  https://$server_name/actionview/api/$1 break;
   }
