### ISSUE TITLE
centos+nginx环境下项目变动无发触发邮件通知

### ISSUE THREAD

**Issue by shakermaker1984** [lxerxa/actionview#118]
centos+nginx环境安装，管理员系统设置测试邮件发送是成功的，但是在项目中无论新建还是修改问题都无法触发邮件通知，之前用docker安装是可以触发的

**Comment by lxerxa** [comment]
是否配置定时器？
* * * * * php /var/www/actionview/artisan schedule:run >> /dev/null 2>&1

**Comment by lxerxa** [comment]
是否配置定时器？wiki里最后一步。

**Comment by shakermaker1984** [comment]
crontab配置了，不然系统设置里也没法发送测试邮件。影响邮件发送的地方还可能有哪些呢？安装环境有https，大部分端口是封闭的，465应该开的不然也发不了测试邮件

**Comment by lxerxa** [comment]
测试邮件发送不需要crontab的。如果测试邮件发送成功的话，应该是 crontab的问题了。

**Comment by shakermaker1984** [comment]
重新配置了一下crontab后可以发送邮件了，谢谢
