### ISSUE TITLE
请问升级的步骤如何？

### ISSUE THREAD

**Issue by matthewxmzhang** [lxerxa/actionview#12]
背景：
之前用docker的方式部署了一版本。假设已经投入使用，已经有业务使用数据。
问题：
请问有建议的升级步骤吗？
我想到的方法：
备份data/db &&  data/uploads数据。
然后把已有的镜像删除后重新按照docker的安装方式安装后，再用备份的data/db &&  data/uploads数据还原？ 如果用该方法，会覆盖了actionview新版的数据库表？

**Comment by lxerxa** [comment]
最新的docker web镜像已push

**Comment by matthewxmzhang** [comment]
谢谢，明白。我好奇的是，假如数据库表结构发生变化了的情况呢？有好的升级建议吗？

**Comment by lxerxa** [comment]
这个就比较复杂了，可能需要具体问题具体分析了，代码升级时尽量避免这种情况，实在万不得已才改动。
