### ISSUE TITLE
看板中新增列时检索不到状态

### ISSUE THREAD

**Issue by guolujun** [lxerxa/actionview#120]
谢谢作者！
在测试功能时，打算建一个新列，但无法搜索到“状态”：
![图片](https://user-images.githubusercontent.com/66941227/85027128-22873900-b1ac-11ea-989c-a013e5fd861d.png)

导致新建的列用不了。
现在只能用三个默认的列“开始”， “处理中“，”完成".

**Comment by lxerxa** [comment]
因为所有的问题状态都分布在现有列上了，解决办法：从某列上移除一个状态，然后该状态就可用到新建的列上了，或者新建个状态。

**Comment by iFrankGuo** [comment]
果然如此！谢谢！
如果没有任何可用的状态存在，在搜索框那里加一个提示例如“无可用状态”可能会好一点？个人想法，仅供参考！

**Comment by lxerxa** [comment]
好的，谢谢您的建议。
