### ISSUE TITLE
用Docker运行1.11.1--经常遇到Suspicious activity has occured on your IP address and you have been denied 错误

### ISSUE THREAD

**Issue by wangyjx** [lxerxa/actionview#121]
在内网以docker方式运行actionview 1.11.1, 经常遇到用户无法登录，或者登录后什么都看不见的情况，
重启 docker实例后，问题消失，但是不一定什么时候会再出现，整个系统就只有几个用户。

查docker日志发现如下错误:

[2020-06-19 10:15:55] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Illuminate\Cookie\Middleware\EncryptCookies::encrypt() must be an instance of Symfony\Component\HttpFoundation\Response, array given, called in /var/www/actionview/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php on line 59 in /var/www/actionview/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:123
Stack trace:
#0 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Cookie\Middleware\EncryptCookies->encrypt(Array)
#1 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#4 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#5 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#8 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#9 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/actionview/app/Http/Middleware/ArrangeResponseData.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 [internal function]: App\Http\Middleware\ArrangeResponseData->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/actionview/app/Http/Middleware/AccessLogs.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: App\Http\Middleware\AccessLogs->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /var/www/actionview/app/Http/Middleware/TrimStrings.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: App\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#32 /var/www/actionview/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#33 {main}
[2020-06-19 10:15:55] production.ERROR: Cartalyst\Sentinel\Checkpoints\ThrottlingException: Suspicious activity has occured on your IP address and you have been denied access for another [739] second(s). in /var/www/actionview/vendor/cartalyst/sentinel/src/Checkpoints/ThrottleCheckpoint.php:146
Stack trace:
#0 /var/www/actionview/vendor/cartalyst/sentinel/src/Checkpoints/ThrottleCheckpoint.php(117): Cartalyst\Sentinel\Checkpoints\ThrottleCheckpoint->throwException('Suspicious acti...', 'ip', 739)
#1 /var/www/actionview/vendor/cartalyst/sentinel/src/Checkpoints/ThrottleCheckpoint.php(71): Cartalyst\Sentinel\Checkpoints\ThrottleCheckpoint->checkThrottling('check', Object(Cartalyst\Sentinel\Users\EloquentUser))
#2 /var/www/actionview/vendor/cartalyst/sentinel/src/Sentinel.php(640): Cartalyst\Sentinel\Checkpoints\ThrottleCheckpoint->check(Object(Cartalyst\Sentinel\Users\EloquentUser))
#3 /var/www/actionview/vendor/cartalyst/sentinel/src/Sentinel.php(244): Cartalyst\Sentinel\Sentinel->cycleCheckpoints('check', Object(Cartalyst\Sentinel\Users\EloquentUser))
#4 /var/www/actionview/vendor/cartalyst/sentinel/src/Sentinel.php(659): Cartalyst\Sentinel\Sentinel->check()
#5 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Cartalyst\Sentinel\Sentinel->getUser()
#6 /var/www/actionview/app/Http/Middleware/AccessLogs.php(27): Illuminate\Support\Facades\Facade::__callStatic('getUser', Array)
#7 [internal function]: App\Http\Middleware\AccessLogs->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /var/www/actionview/app/Http/Middleware/TrimStrings.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: App\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#20 /var/www/actionview/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#21 {main}
[2020-06-19 10:15:55] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function send() on array in /var/www/actionview/public/index.php:56
Stack trace:
#0 {main}
[2020-06-19 10:15:55] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Error: Call to a member function send() on array in /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:107
Stack trace:
#0 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(84): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in /var/www/actionview/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:107
Stack trace:
#0 {main}

请问如何处理呢

**Comment by lxerxa** [comment]
ActionView 有“安全登录保护”机制，  如果多次密码输入错误就会出现该提示。

**Comment by wangyjx** [comment]
> ActionView 有“安全登录保护”机制，  如果多次密码输入错误就会出现该提示。

这个理解，不过有两个问题:
1. 一个用户出了这个问题以后，会影响全部用户.  其他用户即使登录，也显示不了任何项目了。
2. 多次输错密码应该给一个合适的提示，比如剩余登录次数，暂停登录时间几分钟之类的。 现在这种提示，大多数用户并不明白发生了什么.  

一点建议

**Comment by lxerxa** [comment]
1. 有两种保护机制: 基于用户的和基于IP的，基于IP的该机器其他用户访问也会有问题了。
2. ok，这个后续可以再优化一下。

**Comment by wangyjx** [comment]
👌
