### ISSUE TITLE
Feature request :  是不是可以考虑一下增加 问题模板

### ISSUE THREAD

**Issue by wangyjx** [lxerxa/actionview#122]
是不是可以考虑增加问题模板功能，管理员可以自定义各类问题的模板，减少使用时输入的时间

**Comment by lxerxa** [comment]
现在应该是支持的，不同类型的问题可以关联不同的界面。

**Comment by wangyjx** [comment]
@lxerxa,  这个我知道的，不过我的意思是说，  比如 缺陷，我是否能预先定义   缺陷的标题开头， 缺陷的标准描述内容模板，比如


_重现步骤:
1.
2.
3.

期望结果:

实际结果:_

**Comment by lxerxa** [comment]
@wangyjx  可以考虑一下两个解决方案：
1. 定义几个字段（比如：重现步骤，期望结果，实际结果）来结构化数据；
2. 描述字段设置默认值；

**Comment by wangyjx** [comment]
好的，我试试
