### ISSUE TITLE
看板无法显示指定了“解决的版本”的问题

### ISSUE THREAD

**Issue by wangyjx** [lxerxa/actionview#123]
版本1.11.1

项目中有一个任务看板:
类型是Kanban,      全局过滤条件为: 类型～任务,子任务 | 状态～开始,进行中,已完成,重新打开    没有其他条件了

现在新增加了一个  任务类型的问题
状态为“开始”
指定了解决的版本信息

现在发现，如果指定了解决的版本，任务在“任务看板”中看不到；反之，如果清空“解决的版本”，任务会出现在“任务看板”的开始泳道中，这个和全局过滤条件不符合，是不是一个bug?

**Comment by lxerxa** [comment]
Kanban类型就是这样设计的，只显示没有解决版本的，解决版本是通过发布时统一设置的，如果手动设置了问题的解决版本就不会在看板显示了。

**Comment by wangyjx** [comment]
好的，明白了， 我可以用影响版本  来设置相关的值对吧

**Comment by lxerxa** [comment]
是的，看板的展示 和 影响版本的值无关。
