### ISSUE TITLE
actionview无法登陆

### ISSUE THREAD

**Issue by SilkLee** [lxerxa/actionview#124]
安装完CentOS Installation - Nginx之后，输入用户名密码，无法登陆，已经重新安装了两遍了，安装环境在Centos7上的，恳请作者指点一二

**Comment by lxerxa** [comment]
信息太少，不好定位，翻翻以前的问题记录，看看有没有同样的问题。

**Comment by SilkLee** [comment]
![image](https://user-images.githubusercontent.com/37491125/86767377-79cb4b80-c07e-11ea-9dad-de1bf232f861.png)

**Comment by SilkLee** [comment]
执行这个命令时出现了问题composer install --no-dev

**Comment by lxerxa** [comment]
应该不是这个问题吧，最终还是下载下来了，只是换了个源。

**Comment by SilkLee** [comment]
我严格按照文档上的步骤做的 郁闷

**Comment by lxerxa** [comment]
Q: CentOS 安装完后，api访问报错，查看日志发现Log写入报错
A: 查看SELinux状态，如果开启状态，请将其关闭

是不是这个原因？

**Comment by SilkLee** [comment]
虽然没有去查log，但是确实是SElinux这个原因，另外，如何给用户授予超级管理员的权限，好像做不到

**Comment by lxerxa** [comment]
![image](https://user-images.githubusercontent.com/5182909/86867305-2bad5b00-c105-11ea-85d5-c7672dd4c97c.png)
是这个角色吗？

**Comment by SilkLee** [comment]
这个我设置了 我加你QQ了 你同意一下吧 我提供一些浅薄的建议

**Comment by lxerxa** [comment]
可以发我邮件吧，qq现在不太方便。

**Comment by SilkLee** [comment]
添加成员的时候，需要一个个去输入名字，然后一个个点才行。期望鼠标点过去的时候直接显示成员列表，然后选择多个

**Comment by lxerxa** [comment]
如果一个企业人员多的话可能就不太合理了，只有添加成员时需要这样，进入项目之后就可以直接选了。

**Comment by SilkLee** [comment]
如何查看Linux中项目运行的日志，是这个路径么/var/log/nginx/，还是别的路径呢

**Comment by lxerxa** [comment]
storage/log

**Comment by SilkLee** [comment]
![image](https://user-images.githubusercontent.com/37491125/86990845-279a3f80-c1d0-11ea-9d19-2cc0aebcc819.png)这个评价在哪边弄的，我这边没有，是需要在哪个地方设置吗

**Comment by lxerxa** [comment]
没明白意思，最好再新建个问题吧。
