### ISSUE TITLE
Updated user email is not synced to system roles.

### ISSUE THREAD

**Issue by git9am** [lxerxa/actionview#128]
**Reproduce:**
always

**Steps:**
- add user A to the system admin list
- update user A's email
- check the system admin list

**Expected:**
user A's email is updated in the system admin list

**Actual:**
user A's email is still the old one

**Investigation:**
UserController.update is not updating the sys_setting collection in the database. We might address this issue by storing only the user's id in the sys_setting record.

**Comment by lxerxa** [comment]
最初的设计是不支持用户修改邮箱的。如果要修改，建议删除掉原来的，再新建一个。
