### ISSUE TITLE
子任务菜单错误 and 多级子任务？

### ISSUE THREAD

**Issue by flyinghail** [lxerxa/actionview#13]
已有子任务右侧菜单
![default](https://user-images.githubusercontent.com/157430/39691665-de5ff6ce-5210-11e8-83c4-93428714fe2f.png)
注意最下面两个是：“创建子任务”和“转换为子任务”

新建子任务之后右侧菜单
![default](https://user-images.githubusercontent.com/157430/39691704-fdd6082c-5210-11e8-81d8-6e07d0f8ae1c.png)
最下面是“转换为标准问题”

刷新页面后，图二中的菜单会变成和第一个图片一样
看起来第二个图应该是正确的

不过，如果按照正确的显示，就没法实现多级子任务了吧？
错误的显示，倒是可以设置成多级子任务

像 kanboard，也是只有一层子任务，不过可以给问题设置 link：“is a child of” 和 “is a parent of” 设置两个问题的关系

**Comment by lxerxa** [comment]
首先谢谢你的反馈！
1. 菜单显示的确是Bug，我会尽快修改的；
2. 只支持一级子任务，不支持多级；
3. ActionView也有Link功能，支持的是另外6种，没有你说的那两种；

**Comment by flyinghail** [comment]
我看到了 Link  
所以，是否可以有一个管理 Link 的功能? 就像管理 问题类型/状态 这类  
感觉 “is a child of” 和 “is a parent of” 还是会有点用处的

下图是 kanboard 中的 link labels 管理：
![link-labels](https://user-images.githubusercontent.com/157430/39695175-4976e1c4-521c-11e8-9f98-b7f18faa8b23.png)

**Comment by lxerxa** [comment]
提议很好，当时也想把Link做成动态配置的，就是你说的Link管理功能，后来由于时间关系，以及实际使用过程中主要用到了现在集成的那几种Link，就暂时只支持那几种了，以后有时间的话可以考虑支持此功能。
