### ISSUE TITLE
actionview疑问点求解

### ISSUE THREAD

**Issue by 927124** [lxerxa/actionview#131]
您好！已经用了actionview一个星期了，有几个疑问希望您帮忙解答下：

1. 任务到期之前可不可以设置邮件通知；我看系统中有通知事件，但是不知道怎么配置
2. wiki是否可以分享给其他人，不需要注册登录的
3. app是不是已经开发好了，在哪可以下载
非常感谢！

**Comment by lxerxa** [comment]
1. 现在的通知是只有触发了某个事件才会发送邮件，没有任务到期之前的提醒，这块一直想做，但没有特别清晰的需求；
2. 不可以；
3. 正在开发taro版，一直没有投入太多的时间，进度不是很理想。

**Comment by 927124** [comment]
好的，期待移动端早日上线😄
