### ISSUE TITLE
初次搭建环境后，页面登记使用默认管理员账号密码登录没反应

### ISSUE THREAD

**Issue by EyuW** [lxerxa/actionview#134]
1、根据https://github.com/lxerxa/actionview/wiki/CentOS-Installation(Nginx)，指导步骤进行安装的。
2、http://xx.xx.xx.xx/actionview/login该界面要求输入账号密码进行登陆，输入user: admin@action.view, password: actionview
3、毫无反应，感觉像是账号密码失败，或者页面跳转异常

**Comment by lxerxa** [comment]
Q: CentOS 安装完后，api访问报错，查看日志发现Log写入报错
A: 查看SELinux状态，如果开启状态，请将其关闭

是不是这个原因？

**Comment by EyuW** [comment]
已经尝试关闭了selinux，但问题仍旧存在
