### ISSUE TITLE
【建议】新增任务或者子任务的时候，form表单不关闭，并且能复制上次的内容。

### ISSUE THREAD

**Issue by RFDeval** [lxerxa/actionview#140]
![image](https://user-images.githubusercontent.com/3634651/95455544-a1dd8a00-09a0-11eb-8599-5279023bfb9e.png)
一个任务下，可能会有很多类似的子任务，新增一个的时候，点击确定，就关闭了，然后再新增下一个，很多内容要重新填写，是否可以来一个保存并新增的功能，下一个任务就不用填写很多内容了，直接复制了上一次的。

**Comment by lxerxa** [comment]
可以用问题的拷贝功能的。

**Comment by lxerxa** [comment]
不过建议也很好，后续可以考虑优化。

**Comment by lxerxa** [comment]
新版本已支持该功能，可以不关闭创建页面，继续创建下一个问题。
