### ISSUE TITLE
【建议】多项目管理模式下，用户组和项目组关联比较好。

### ISSUE THREAD

**Issue by RFDeval** [lxerxa/actionview#141]
actionview是支持多项目管理的，目前用户组和用户一样是系统管理员设定在全局的。
个人建议：

1. - 系统管理员负责系统级别的管理（用户管理、项目管理）
2. - 各项目负责人负责各自项目里群组的创建，以及将用户加入到群组中。

理由：如果用户组和项目关联，这样应该更合适，各个项目的规模不一样，创建的组也不一样，用到的人也不一样。举例说明：用户A可能在项目一中是系统架构师，而在项目二中就是一个高级开发。在项目三中甚至是产品经理。（呵呵，毕竟现在都把大家逼成了复合型人才啊）
请作者考虑。

**Comment by lxerxa** [comment]
您的建议很好，当时开发的时候，考虑如果让用户自己创建群组的话，管理起来可能会混乱。
如果开发这块的话也需好好设计下，比如群组在项目间是否可共享，对哪些用户是可见的等等。

**Comment by lxerxa** [comment]
新版本已支持用户自定义群组，并对其授权。
