### ISSUE TITLE
甘特图

### ISSUE THREAD

**Issue by WolfeeLuo** [lxerxa/actionview#142]
1. 甘特图性能问题. 感觉甘特图有性能问题, 体验项目中issue数的展开和折叠有长时间的卡顿.
2. 希望甘特图增加按资源展示. 比如每个开发人员的关联的issue, 从而可以看出每个开发的工时分布. 类似jira的bigpicture插件的workload功能.

**Comment by lxerxa** [comment]
谢谢您的建议，后续考虑优化。
