### ISSUE TITLE
composer install --no-dev安装步骤出现错误

### ISSUE THREAD

**Issue by southbear-club** [lxerxa/actionview#151]
composer install --no-dev 执行这一步安装出现错误

[ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

ubuntu20.04

**Comment by lxerxa** [comment]
php 版本可能太高了。
