### ISSUE TITLE
有宝塔的安装说明么？

### ISSUE THREAD

**Issue by aitu8** [lxerxa/actionview#152]
根据centos nginx安装了一下，一直403.

**Comment by lxerxa** [comment]
木有啊

**Comment by aitu8** [comment]
> 木有啊

啥时候空了出一个嘛。。么么哒

**Comment by kknd222** [comment]
docker镜像：lxerxa/actionview
内部端口80映射到外部端口
但是我部署后，输入用户名密码没登陆成功
