### ISSUE TITLE
部署完成，提交登录出现404错误

### ISSUE THREAD

**Issue by yangjiafus** [lxerxa/actionview#153]
**安装环境** ：CentOS Installation(Nginx)
**actionview版本** ：1.9.3v
**登录异常截图** ：
![image](https://user-images.githubusercontent.com/31515505/110752986-ebe4d780-8280-11eb-8042-d7000112c185.png)
需求：
按照CentOS Installation(Nginx)去做的安装配置，最后登录报/api/session 404，是不是nginx里面的配置少了啥子，或者其他的问题？

**Comment by lxerxa** [comment]
应该是nginx服务器配置的问题。

**Comment by yangjiafus** [comment]
我的ng配置内容与社区提供的配置，仅对域名做了变更，其他没变，能否帮我看看具体是哪儿配置错误了。配置如下：
`server {
    listen 80;
    listen [::]:80;

    root /var/www/actionview/public;

    server_name localhost;

    client_max_body_size 100M;

    location ^~ /actionview/api {
        index index.html index.htm index.php;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ^~ /actionview {
        add_header Cache-Control 'no-cache, must-revalidate, max-age=0';
        alias /var/www/actionview/public/;
        index index.html index.htm index.php;
        try_files $uri $uri/ /index.html$is_args$args;
    }

    location / {
       add_header Cache-Control 'no-cache, must-revalidate, max-age=0';
       index index.html index.htm index.php;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ \.php {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        try_files $uri =404;
    }
}`

**Comment by lxerxa** [comment]
api/session 前边的contextpath里有actionview字样吗？

**Comment by yangjiafus** [comment]
没有

**Comment by yangjiafus** [comment]
没有。我在源码里看见有完整的路径：actionview/api/session
但是加上后又报500的错误了。

**Comment by lxerxa** [comment]
应该有的。

**Comment by yangjiafus** [comment]
完整请求头如下：
Request URL: http://fordsctest.cmal.com.cn/api/session
Request Method: POST
Status Code: 404 Not Found
Remote Address: 192.168.89.84:80
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 555
Content-Type: text/html
Date: Thu, 11 Mar 2021 08:32:28 GMT
Server: nginx/1.16.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6
Connection: keep-alive
Content-Length: 53
Content-Type: application/json;charset=UTF-8
Host: fordsctest.cmal.com.cn
Origin: http://fordsctest.cmal.com.cn
Referer: http://fordsctest.cmal.com.cn/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
{email: "admin@action.view", password: "actionview"}
email: "admin@action.view"
password: "actionview"

**Comment by lxerxa** [comment]
路由必须有actionview前缀，如果是返回 500, 可调查500的问题，请查看storage/logs的最新日志。

**Comment by yangjiafus** [comment]
好的，我刚刚查看了服务日志，发现是服务器权限问题，我勒个鬼！
`PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/actionview/storage/logs/laravel-2021-03-11.log" could not be opened: failed to open stream: Permission denied in /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107`
感谢,后面应该知道怎么解决了

**Comment by dabing521** [comment]
路由必须有actionview前缀，如果是返回 500, 可调查500的问题，请查看storage/logs的最新日志 这个storage/logs下面没有日志是怎么回事？我的也是报500错误
