### ISSUE TITLE
求再在黑群晖中的安装方法

### ISSUE THREAD

**Issue by huzichai** [lxerxa/actionview#155]

**Comment by huzichai** [comment]
自己安装好了。
首先在群晖的docker套件中下载actionview的是三个镜像。
第二，到github上下载代码放到群晖上。
最后在群晖的ssh下，cd到第二步放代码的目录中的docker的文件夹执行

**Comment by lxerxa** [comment]
👍

**Comment by huzichai** [comment]
> 👍
感谢大佬们的付出，系统很好用。
