### ISSUE TITLE
新添加用户后，用户密码是多少？

### ISSUE THREAD

**Issue by jdkysq** [lxerxa/actionview#16]
我添加用户后即使重置也不知道密码是多少，并且 配置了邮件，找回密码不可用，非常无奈，用户注册也没有开放。除了自身管理员账号能登录之外，其他人根本无法协作。

**Comment by lxerxa** [comment]
1. 如果没有配置 “默认登录邮箱域名“，请使用邮箱登录；
![image](https://user-images.githubusercontent.com/5182909/41089109-a488b6fe-6a73-11e8-8501-9685cd85dda2.png)
2. 如果配置了的话，可使用邮箱前缀登录；

默认密码都是:actionview

**Comment by lxerxa** [comment]
是否可以？

**Comment by jdkysq** [comment]
> 1. 如果没有配置“默认登录邮箱域名”，请使用邮箱登录;
>    ![图片](https://user-images.githubusercontent.com/5182909/41089109-a488b6fe-6a73-11e8-8501-9685cd85dda2.png)
> 2. 如果配置了的话，可使用邮箱前缀登录;
> 
> 默认密码都是：的ActionView

I'm sorry that I didn't reply in time because I was busy in mainland China.We re-selected other alternatives that day and we will re-use them at the appropriate time.

**Comment by jdkysq** [comment]
> 是否可以？

不好意思，因为在中国大陆，并且平时比较忙，没能及时回复。我们当天重新选择了其他替代品，我们将在合适的时候重新使用。
