### ISSUE TITLE
有没有一个详细的升级指引

### ISSUE THREAD

**Issue by daiguangbao** [lxerxa/actionview#160]
通过 git pull 升级了，然后在登录界面一直登录不了。
从浏览器看到若干js的错误
Failed to load resource: the server responded with a status of 404 (Not Found)      /api/session:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load SourceMap: Could not load content for http://xxx.com/scripts/common.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by lxerxa** [comment]
清下缓存

**Comment by daiguangbao** [comment]
尝试过清除浏览器的缓存了，还是不行。
我现在是从1.8升到1.12的，服务器端需要改什么东西？@lxerxa 谢谢

**Comment by daiguangbao** [comment]
@lxerxa 你是对的。至少我多清了几次之后可以了。
