### ISSUE TITLE
config.sh 執行錯誤

### ISSUE THREAD

**Issue by steven0726** [lxerxa/actionview#166]
環境 : CentOS (7.9.2009) + Apache (2.4.6)

依照安裝順序執行 sh config.sh 時出現多個錯誤訊息

![image](https://user-images.githubusercontent.com/17433986/121941126-79086280-cd81-11eb-9372-058ef624beb9.png)

謝謝

**Comment by lxerxa** [comment]
composer install 应该没成功。

**Comment by steven0726** [comment]
> composer install 应该没成功。

我是安裝 https://getcomposer.org/ 所提供的 composer

這樣算是有安裝成功吧 ?
![image](https://user-images.githubusercontent.com/17433986/122067268-069d8e00-ce26-11eb-9aca-7bd0304638bc.png)

謝謝

**Comment by lxerxa** [comment]
需要用composer安装actionview的依赖。

composer install --no-dev
