### ISSUE TITLE
Unexpected token 项目中心一直转圈圈刷新不出数据，点进项目里面能正常显示

### ISSUE THREAD

**Issue by third8923** [lxerxa/actionview#167]
http://192.168.2.182:8000/actionview/myproject

DevTools failed to load source map: Could not parse content for http://192.168.2.182:8000/actionview/scripts/common.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for http://192.168.2.182:8000/actionview/scripts/app-1ea0ca63a4daa006cd3e.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for http://192.168.2.182:8000/actionview/assets/project-1ea0ca63a4daa006cd3e.js.map: Unexpected token < in JSON at position 0

**Comment by lxerxa** [comment]
这个应该是缓存的问题。

**Comment by lxerxa** [comment]
这个应该是缓存的问题。
