### ISSUE TITLE
我想在邮件中加一些内容

### ISSUE THREAD

**Issue by fdjaoifjoidz** [lxerxa/actionview#168]
于是去修改了resources\views\emails\issue.blade.php中的前端代码，重启docker各个容器后，但是没有生效，请问该怎么做

**Comment by fdjaoifjoidz** [comment]
![image](https://user-images.githubusercontent.com/86825488/124245331-7adc6f00-db52-11eb-80f0-db5974b9983e.png)

**Comment by lxerxa** [comment]
需要修改cron容器

**Comment by fdjaoifjoidz** [comment]
> 需要修改cron容器
呃呃  需要在哪里怎么修改呢
