### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [lxerxa/actionview#169]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by lxerxa** [comment]
We have received your email and will deal with it as soon as possible, thank you!

**Comment by amammad** [comment]
Dears, Can I ask you to just validate my repirts as they will be remain hidden until you fix them? 
best regards.

**Comment by amammad** [comment]
Can I ask you read this my dear?
I losing my hope about bounties that huntr.dev want to pay me for found security vunls on your repo.

About Huntr.dev procedure :
there is four step for you as a maintainer or as security team that access to reports on the Huntr platform

1.you see the reports and check them if they are valid or not
2.if they are valid you validate them and I get my bounty from Huntr( the reports still hidden from public )
3.After step 2 you create a fix commit on GitHub them submit it
3.After that you submit the fix on Huntr and the report will be published
If you are in step 2, you can validate my report as they will remain hidden until you create a fix commit and submit it.
And please validate my reports If you evaluate them as a correct issues.
Best regards, Amammad.

**Comment by lxerxa** [comment]
I don't know how to fix it, look forward to your pr.

**Comment by amammad** [comment]
I tell you but if the reports are correct I want to ask you to validate them, is it ok for you?
The easiest way is that you make samesite flag of all cookies to 'lax'.
the other ways is that you set cstf lrotection token on each endpoint/durectory

**Comment by amammad** [comment]
The fix :

In config/session.php

'same_site' => "strict",

please Give me some feedback about it

**Comment by lxerxa** [comment]
I know the principle of crsf, but still don't know how to modify the code. Recently I'm very busy, will study it when have time.

**Comment by amammad** [comment]
OK 
can I just ask you to validate reports please? 
they will be hidden until you submit a fix.

**Comment by amammad** [comment]
I study Multiple websites and find out that we can use 

'same_site' => "strict",
 
in config/session.php file

I ask you to try it and apply it on demo link so I test it quickly and give you the feedback.

**Comment by amammad** [comment]
My dear there are 8 reports of mine in huntr.dev an you only validate one of them

**Comment by amammad** [comment]
You can see all the reports that related to your repo on this link 

https://huntr.dev/users/lxerxa/reports

**Comment by amammad** [comment]
Hey dear can you give only 3 minutes and validate all reports ? I losing my motivation.

**Comment by amammad** [comment]
Hello my dear 
These reports still in pending mode you can validate them only in 2 minutes... can I ask you validate them ?

https://huntr.dev/bounties/4a8f462c-4315-46b5-bad0-c484f2d54443/
https://huntr.dev/bounties/46960516-fc23-4e62-9af7-15687b04af23/
https://huntr.dev/bounties/98babcaf-0ac7-43da-825c-3ad021ba09db/
https://huntr.dev/bounties/0a6df526-1b98-41d7-8fd4-3ed439e630be/
https://huntr.dev/bounties/8079d28a-e790-4741-8579-ec0839f4a719/
https://huntr.dev/bounties/655887e8-8079-4480-ae9b-596c65f030c9/
https://huntr.dev/bounties/e24de4a2-bced-4017-bf53-82b6cda60629/

**Comment by amammad** [comment]
Hey man can I ask you please to give me just 5 minutes of your time and come into huntr and validate my reports please??

**Comment by amammad** [comment]
Any feedback dear ?

**Comment by amammad** [comment]
Hey man, Can you tell me that you want to validate or invalidate my reports ?
