### ISSUE TITLE
版本升级方式请教

### ISSUE THREAD

**Issue by weifeng2000** [lxerxa/actionview#17]
您好！我们已经部署了1.2.0，想升级到最新版本，直接git pull代码后报错，有没有版本升级 步骤或方案？

**Comment by lxerxa** [comment]
出错原因应该是新版的增加了adldap模块造成的。
版本升级步骤：
1. git pull 代码；
2. 执行安装脚本：sh config.sh
3. 安装依赖： composer install

**Comment by weifeng2000** [comment]
OK，谢谢！
