### ISSUE TITLE
storage目录下文件没有删除

### ISSUE THREAD

**Issue by BisonLeo** [lxerxa/actionview#172]
上传到actionview一个比较大的文件(约20M)后, 虽然在文件中删除了, 而且提示无法恢复, 但实际在服务器上的storage 目录下还是有该文件. 
请问有没有清理残余文件的方法? 
v1.2.6 b4c2418e

**Comment by lxerxa** [comment]
找到文件，可手动删除。

**Comment by BisonLeo** [comment]
但实际文件名都已经hash过 事后是不知道是哪个 而且同一个文件上传后会有不同的名字 我也是按文件大小才偶然发现的有多份拷贝。
建议是拿上传后的文件的大小和开头结尾的部分字节一起计算hash来作为唯一的识别，并在storage中实际删除。
