### ISSUE TITLE
上传文件报upload file errors，code是-11959

### ISSUE THREAD

**Issue by reixuemin** [lxerxa/actionview#173]
暂时不清楚为啥报了这个错，上传的文件是大于100M的zip，刚开始是说Entity is too large，改了NGINX，之后就报这个-11959了，能否看看是配置有错还是代码问题

版本号是1.12.1

**Comment by lxerxa** [comment]
是在wiki里上传文档？可以输出下文件上传真实的错误码看看。

**Comment by lxerxa** [comment]
php.ini 里这两个值也需要修改的，post_max_size和upload_max_filesize

**Comment by reixuemin** [comment]
看了下配置文件里的配置，都是8M之类很小的值，感觉跟这个配置没关系，我也试着改了，还是不行，PHP我记得改配置不用重启什么的吧？ActionView需要重启吗？

**Comment by lxerxa** [comment]
改的是fpm下的php.ini? 修改后需重新启动php-fpm。

**Comment by reixuemin** [comment]
我们这是用docker安装的，总共有3个容器，docker_cron_1，docker_nginx_1，docker_web_1，我是在cron跟web中能搜到php.ini，但是在/etc/php/7.0/cli/php.ini跟/etc/php/7.0/apache2/php.ini，没有你说的fpm

**Comment by lxerxa** [comment]
apache的话， 修改.htaccess 也可以，参照faq.

**Comment by reixuemin** [comment]
行了，谢谢
