### ISSUE TITLE
Webhook新增事件

### ISSUE THREAD

**Issue by reixuemin** [lxerxa/actionview#174]
问下webhook能加多一些事件吗？”编辑事件“貌似是需要点击编辑才会触发的，界面上有些输入框是能直接修改的，例如”负责人“，”描述”等等，这种直接修改的貌似不会触发Webhook，这种你们有计划加下吗？

版本是1.12.1

**Comment by lxerxa** [comment]
我们跟进下这个问题，应该要出发编辑事件。

**Comment by lxerxa** [comment]
新版本会将  分配问题、移动问题、重置问题 事件 都统一归类到编辑问题事件中。(仅适用webhook)
