### ISSUE TITLE
问题类型显示为一串字符

### ISSUE THREAD

**Issue by fdjaoifjoidz** [lxerxa/actionview#176]
![VY8LQ954F({I TGA8YWV)(C](https://user-images.githubusercontent.com/86825488/133363133-b12c9706-0ca7-49f1-a002-66ec16ea88ff.jpg)
只有创建问题时，显示是对的。
公式用的$issue['type']，想问下如何正确取值

**Comment by fdjaoifjoidz** [comment]
还有  关联用户应该怎么取

**Comment by lxerxa** [comment]
需要通过类型id再查询，参见发送邮件文件SendEmails.php：

                $type = Type::find($issue['type']);
                $issue['type'] = $type ? $type->name : '-';
