### ISSUE TITLE
配置的工作流、字段、界面等可以导出吗

### ISSUE THREAD

**Issue by HuBoZhi** [lxerxa/actionview#177]
我想要迁移这些数据的有什么方案吗

**Comment by lxerxa** [comment]
不可以。

**Comment by HuBoZhi** [comment]
我想要迁移这些数据的有什么方案吗，直接将数据库的内容复制过去？

**Comment by lxerxa** [comment]
可以复制数据库中相应的数据文件。

**Comment by HuBoZhi** [comment]
我是Docker部署的要复制的文件包括哪些呢？
![image](https://user-images.githubusercontent.com/36149293/134918136-f934eb69-e7fe-4515-bc9a-73b1f0c6dc81.png)
这两个吗

**Comment by HuBoZhi** [comment]
OK~多谢了
