### ISSUE TITLE
Amammad from huntr.dev

### ISSUE THREAD

**Issue by amammad** [lxerxa/actionview#178]
Hey man how are you today?
Can I ask you just click on validate button of these reports please ?

https://github.com/lxerxa/actionview/issues/169#issuecomment-920310825

best regards.

**Comment by amammad** [comment]
This is a long time from that I report the vulnerabilities and I losing my motivation, Please don't forget to support security researchers like me .

thanks.

**Comment by lxerxa** [comment]
很疑惑，为什么同样的问题出这么多报告，好像没意义？
