### ISSUE TITLE
任务进度和任务状态（解决结果）的同步问题

### ISSUE THREAD

**Issue by fly2tomato** [lxerxa/actionview#180]
![image](https://user-images.githubusercontent.com/11885550/139271628-0689559e-67ca-43b0-857f-5b30ce62d6af.png)
当点击**已解决**时，对应的进度是否可以自动更新为100%？

**Comment by lxerxa** [comment]
经讨论后，建议可通过流程配置解决该同步问题：在配置“已解决”动作时，关联一个动作界面，该界面只有一个进度字段即可。
![image](https://user-images.githubusercontent.com/5182909/139526824-2566c6f4-db22-428b-a4f3-ac604f61fa01.png)

**Comment by fly2tomato** [comment]
好的 感谢~

**Comment by fly2tomato** [comment]
但是这样貌似会带来一个新的问题： 
会导致git commit代码时，"xx-yy-zz dddd"对应的git记录和状态修改（1001->2001）无法同步到actionview上了（因为在2001后面增加了一个进度的界面）

**Comment by lxerxa** [comment]
如果通过webhook触发的话，只能在流程配置里多加个置后处理项了，争取下个版本加上。

**Comment by lxerxa** [comment]
新版本已增加该置后处理项，如图，请重新配置流程。
![image](https://user-images.githubusercontent.com/5182909/141390151-7ac0cc78-ed3b-4684-a8fb-f856b857b141.png)
