### ISSUE TITLE
升级后，设置问题标签报错“系统错误”

### ISSUE THREAD

**Issue by huzichai** [lxerxa/actionview#181]

**Comment by huzichai** [comment]
升级前是1.12.0，给问题分配标签上正常的。升级到1.12.8后，一给问题分配标签就报错“系统错误”

**Comment by huzichai** [comment]
![Uploading Screenshot_2021-11-01-16-57-12-211_com.android.chrome.jpg…]()

**Comment by lxerxa** [comment]
了解，下个版本修复。

**Comment by lxerxa** [comment]
修复代码提交到master了，更新下即可。

**Comment by huzichai** [comment]
感谢，感谢！
