### ISSUE TITLE
docker运行时，无法发送邮件

### ISSUE THREAD

**Issue by jeff-ld0411** [lxerxa/actionview#183]
docker里可以正常运行，但配置邮件服务器后，发送测试邮件总是失败，服务器地址和帐号在foxmail里都正常，不清楚是什么原因？

**Comment by lxerxa** [comment]
加密方式用换下呢？

**Comment by michkish** [comment]
> docker运行的问题好像没有解决，提供的#69的解决方案和提出人遇到的问题感觉都不一样，描述不清楚，不可能说一个非加密的方式用了ssl解密通讯就搞定了。

我这里分享下，是我配置邮件的问题，发送邮箱的发信地址和SMTP服务器的账号所对应的邮箱地址填写有误（正好差了一个字母）。更正之后就没有问题了。
