### ISSUE TITLE
关联用户和期望开始时间的问题

### ISSUE THREAD

**Issue by fdjaoifjoidz** [lxerxa/actionview#184]
想问一下邮件里有没有办法，把关联用户放出来，php代码怎么写呢，期望开始时间能不能取默认值，取问题创建时间或者当前时间都可以。

**Comment by lxerxa** [comment]
1. 关联用户，找个懂PHP，简单做个二次开发就可以。
2. 期望开始时间，这个问题我们考虑下，看下个版本怎么兼容下好。

**Comment by fdjaoifjoidz** [comment]
可以指点一下么，比如用$data['contents'] ，$issue['expect_start_time'])可以取备注和时间，关联用户related_users从哪里获取呢

**Comment by lxerxa** [comment]
将来做个邮件模板配置功能吧，请关注。
