### ISSUE TITLE
能否使用其他框架重写？

### ISSUE THREAD

**Issue by limingxinleo** [lxerxa/actionview#185]
ActionView的作者，你好，我偶然间发现了这个项目，觉得十分有趣，我能否重新创建一个项目使用其他框架对后端部分进行重写，并进行开源。

很期待收到你的回复。

**Comment by lxerxa** [comment]
意义是什么？

**Comment by lxerxa** [comment]
当然可以，不过意义是什么？

**Comment by limingxinleo** [comment]
意义是给框架，写一个功能全且能正常使用的demo

之前的demo都更偏向于特定功能，而不是一个功能完备且可以使用的。

从0开始写，显然压力太大了😂

**Comment by lxerxa** [comment]
actionview已经不是一个demo了，完成度很高了，使用的企业也不少，包括我们也一直在用。如果重新写，的确压力不小。

**Comment by limingxinleo** [comment]
是的啊，我也看着完成度很高，实用性也很高，所以才有了这个想法，顺便还能训练一下手下的人

**Comment by lxerxa** [comment]
可以，有问题随时可咨询我。

**Comment by limingxinleo** [comment]
好的，谢谢
