### ISSUE TITLE
前端代码可以使用哪个 commit？

### ISSUE THREAD

**Issue by limingxinleo** [lxerxa/actionview#186]
我看到最新的 master 和本项目里依赖的子模块，差距有点大了

**Comment by limingxinleo** [comment]
本项目里 https://github.com/lxerxa/actionview-fe.git 子模块的 commit 还是 18年的版本

**Comment by lxerxa** [comment]
以前端库为主。

**Comment by limingxinleo** [comment]
最新的库，好像有版本冲突

**Comment by lxerxa** [comment]
如果可以的话，把前端也重写了吧。

**Comment by limingxinleo** [comment]
前端，我无能为力了。。。。🤣🤣
