### ISSUE TITLE
以下几个问题

### ISSUE THREAD

**Issue by 26597925** [lxerxa/actionview#19]
1.邮箱不能有中划线。（但是很多人的域名和邮箱加了中划线）
2.局域网会被限制登录，貌似被别人尝试很多次了，所有人都不能登录了。

**Comment by lxerxa** [comment]
第一个问题我看下；第二个问题可能是密码输入错误次数太多，15分钟后请重试。

**Comment by 26597925** [comment]
第二个问题，是局域网其他人也不能登录。是密码输错了两次就这样。

**Comment by lxerxa** [comment]
限制分两种：1. 用户限制；2.ip限制；

用户限制就是同一个用户同一时间段登录错误次数太多，可能多台机器都在用这个用户登录，这样这个用户就不能再登录了，15分钟应该就可以了。

另外，这个限制可以后台配置是否启用。有好几个用户提到这个问题了。

**Comment by lxerxa** [comment]
默认配置的应该是5 次

**Comment by 26597925** [comment]
哦，好的，谢谢！

**Comment by lxerxa** [comment]
最近会发布个新版本，把这个限制是否启用 做成后台可配置的，请关注。

**Comment by 26597925** [comment]
好的，谢谢！一直关注中，你这个系统做的挺好的，我很喜欢。

**Comment by lxerxa** [comment]
谢谢夸奖！

**Comment by 26597925** [comment]
不用谢，是真的，我还推荐给了几个朋友，我朋友也觉得挺好，还说Jira的中国式体验，因为很多人都用破解版的Jira，有你这东西了，大家都换了，挺好。

**Comment by lxerxa** [comment]
比jira轻，用起来很简单，有什么问题欢迎提出，一起让他变得很好吧。

**Comment by 26597925** [comment]
好的，没问题，我反正现在会用，我多体验，有体验不足或者bug类的，我会在这里提出来。
