### ISSUE TITLE
看板出错：要完成的sprint必须是活动的

### ISSUE THREAD

**Issue by fly2tomato** [lxerxa/actionview#190]
![image](https://user-images.githubusercontent.com/11885550/147812720-805de73b-ecab-46f5-b9dd-7f6c2332d16b.png)
![image](https://user-images.githubusercontent.com/11885550/147812775-161a8464-ab8e-49d3-9288-ab0112ec1ed0.png)

**Comment by fly2tomato** [comment]
![image](https://user-images.githubusercontent.com/11885550/147812809-ba06737c-7d69-47d5-a2d8-76a701ec4f51.png)
当前看板是活动的。。。。

**Comment by lxerxa** [comment]
了解，估计版本升级影响的，尽快修复！

**Comment by lxerxa** [comment]
我看现网没问题啊，版本是？是不是该sprint在另外一个页面被处理了？
