### ISSUE TITLE
登錄密碼錯誤

### ISSUE THREAD

**Issue by p112627701** [lxerxa/actionview#191]
![image](https://user-images.githubusercontent.com/85160237/150918617-8f21bf1c-c653-4e4e-a72e-ce0b97da3734.png)
第一次登入密碼一直登入不進去

**Comment by p112627701** [comment]
輸入password: actionview

**Comment by p112627701** [comment]
我已解決了

**Comment by kknd222** [comment]
怎么解决的？
我也登陆不上去，点击刷新一下，没动静了
