### ISSUE TITLE
安装完成后登录报404

### ISSUE THREAD

**Issue by fc1986** [lxerxa/actionview#192]
用Linux nginx方式安装之后，访问页面，登录请求http://ip:port/actionview/api/session报404

**Comment by fc1986** [comment]
nginx配置如下：
![image](https://user-images.githubusercontent.com/61484209/153566646-a0a93230-b709-4fdc-816f-f31857487b15.png)

**Comment by lxerxa** [comment]
root写错了吧？

**Comment by fc1986** [comment]
> root写错了吧？

是的，是的，多写了一个i
