### ISSUE TITLE
已同步的LDAP用户再次被同步后出现重复ID问题

### ISSUE THREAD

**Issue by sansam** [lxerxa/actionview#195]
问题描述：同步至ActionView的LDAP用户，当在LDAP系统中挪动其OU后，再次执行导入，会出现2个ID相同的账号，同时登录提示密码错误。
重现步骤：
1. 配置好LDAP，执行【同步数据】
2. 使用导入的账号登录ActionView，可以登录成功
3. 在LDAP系统中修改账号的OU
4. 再次执行【同步数据】
5. 使用同样的账号登录登录ActionView，提示密码错误
6. 检查ActionView的用户列表，发现有2个ID相同的账号，其中一个显示【禁用】

![image](https://user-images.githubusercontent.com/4145189/156083388-f4e69dec-ef76-4609-bac3-eb732ae12212.png)
![image](https://user-images.githubusercontent.com/4145189/156084133-39dc3371-06e1-425e-94f5-9a71b69893bb.png)

**Comment by lxerxa** [comment]
有人提过同样的问题，但是我们的环境一直未再现现象，我们跟进下，或者加QQ：2909532487

**Comment by lxerxa** [comment]
原因是用户调整 ou 后，dn 也跟着变了导致的。同样的用户出现了两条，这个不好修改，但可保证用户能正常登陆，下个版本修复。

**Comment by lxerxa** [comment]
新版本v1.13.0已发布，用户无法登陆已修复。
