### ISSUE TITLE
PHP5.6不行么...？

### ISSUE THREAD

**Issue by mojie126** [lxerxa/actionview#20]
提示Argument 1 passed to Illuminate\Cookie\Middleware\EncryptCookies::encrypt() must be an instance of Symfony\Component\HffpFoundation\Respose, array given, called in xxx EncryptCookies.php on line 59 and defined

**Comment by lxerxa** [comment]
没问题的，是按照wiki安装的的吗？

**Comment by mojie126** [comment]
是按照文档操作的...mongo是4.0的有问题么...？

**Comment by mojie126** [comment]
CentOS 7.4
但是这个看起来是cookie或session的原因，貌似还跟数据库没关系的时候发生的问题吧...？

**Comment by lxerxa** [comment]
这是log里的，api接口返回什么？

**Comment by mojie126** [comment]
给个接口uri...？

**Comment by mojie126** [comment]
ecode:-99999
emsg:就是上面那些...

**Comment by lxerxa** [comment]
应该是mongo驱动问题，以前其他人也有过类似问题，错误信息不准确。

**Comment by mojie126** [comment]
修改config/database.php里关于mongodb的options里的db
db->database即可...
