### ISSUE TITLE
日志文件位置

### ISSUE THREAD

**Issue by reixuemin** [lxerxa/actionview#201]
能问下你们的日志文件在哪里吗？

我这边升级到1.13.1后文件没法上传了，报500错误，想看看是哪里有问题

如果是storage里面的logs的话，貌似没什么内容
![image](https://user-images.githubusercontent.com/14087655/166858857-e95a6dd0-209f-47ac-a094-62244896fd83.png)

**Comment by lxerxa** [comment]
其他没问题？只有上传文件有问题？

**Comment by reixuemin** [comment]
> 其他没问题？只有上传文件有问题？

嗯，就上传文件有问题，包括附件，复制图片

**Comment by lxerxa** [comment]
建个测试项目，方便远程调试下吗？

**Comment by lxerxa** [comment]
都可以，加qq 2909532487

**Comment by reixuemin** [comment]
> 都可以，加qq 2909532487

你什么时间有空？晚上还是要白天？

**Comment by lxerxa** [comment]
现在就可以
