### ISSUE TITLE
数据读取异常

### ISSUE THREAD

**Issue by Sunny1591719** [lxerxa/actionview#212]
断电之后docker启动失败，通过删除之前的容器，再重新执行docker-compose up代码创建容器，之前新建的几个项目有一个项目数据异常，本来是几十条数据，但概览页面的问题数对不上，只显示几条。请问需要怎么处理解决这个异常问题？

**Comment by Sunny1591719** [comment]
![image](https://user-images.githubusercontent.com/106149091/178405088-bb2f292a-b2e1-443a-8733-9eaa4c164c1f.png)

**Comment by lxerxa** [comment]
参考 #165

**Comment by Sunny1591719** [comment]
你好，试了#165的方法，还是不行，能帮忙看看吗

**Comment by Sunny1591719** [comment]
你好，能通过QQ或其它方式联系请教你吗，现在急着修复数据

**Comment by Sunny1591719** [comment]
我这边试过很多办法都无法解决，现在出现新的问题，能帮忙看看吗，感谢？
![image](https://user-images.githubusercontent.com/106149091/178461012-f0fcca81-e4ab-436e-b73b-4bdec1350fa2.png)
![image](https://user-images.githubusercontent.com/106149091/178461098-b5c0a99d-3ec0-491f-b30c-3d3a7dcea181.png)

**Comment by lxerxa** [comment]
是否已解决？

**Comment by Sunny1591719** [comment]
未解决

**Comment by Sunny1591719** [comment]
怎么能联系到你呢？
