### ISSUE TITLE
字段界面的数据没有了

### ISSUE THREAD

**Issue by Sunny1591719** [lxerxa/actionview#213]
字段的数据没有了，但问题编辑和新建的时候是可以看到
![image](https://user-images.githubusercontent.com/106149091/178863930-07326385-d201-4e3d-a62a-1c70bc786e61.png)
![image](https://user-images.githubusercontent.com/106149091/178864205-2bae2b73-056b-41ce-90ca-c127baed16d2.png)

**Comment by lxerxa** [comment]
是否已解决？

**Comment by Sunny1591719** [comment]
未解决，能怎么联系到你
