### ISSUE TITLE
上传超过100M的文件失败

### ISSUE THREAD

**Issue by tianshixingkong** [lxerxa/actionview#220]
通过docker安装，先执行docker-compose down后修改如下配置再执行docker-compose up，还是上传失败，版本为1.15.1：
![image](https://user-images.githubusercontent.com/114304158/195517787-504fa7c1-5178-40e1-bc60-3659d4520280.png)
![image](https://user-images.githubusercontent.com/114304158/195517946-a59f4b70-4fe4-4b3d-a534-c6e091b40127.png)

**Comment by lxerxa** [comment]
需要修改容器里的配置
