### ISSUE TITLE
是否支持查看一个人在所有项目里的任务列表

### ISSUE THREAD

**Issue by lizcao** [lxerxa/actionview#224]
是否支持查看一个人在所有项目里的任务列表

**Comment by lxerxa** [comment]
暂不支持，后续会考虑。

**Comment by lizcao** [comment]
谢谢回复，能支持的话就太好了。还有个问题，我用docker安装的，之前的版本的是1.12.12，我按照FAQ上的说明，进入到容器里代码目录里执行下面步骤，提示执行成功了，但是看版本号还是之前的版本，并没有升级到最新的1.15.2，请问这是什么原因啊？
```
Q: 版本升级步骤有哪些？
A: 1. git pull 代码
  2. 执行安装脚本：sh config.sh
  3. 安装依赖：composer install --no-dev
```
