### ISSUE TITLE
外部用户功能，增加动作id后问题状态未发生变更

### ISSUE THREAD

**Issue by sukekes** [lxerxa/actionview#229]
操作步骤：
1. 新建一个问题，编码为1（项目键值P2022_001）
2. 配置外部用户，启用github并配置面膜
3. github 设置webhook
4. 更新代码，提交并推送到代码仓库（commit使用 P2022_001-1-1002dddd 的形式，1002是解决问题id）
6. 验证问题状态

预期结果： 
1. 问题git提交记录更新
2. 问题状态更新，状态变更为“已完成”

实际结果：
1. 问题状态未更新，仍为“开始”状态

**Comment by lxerxa** [comment]
1002后边有空格吗？

**Comment by sukekes** [comment]
是有空格的。连续试了5次之后，问题状态变更成功了。这个问题我先关闭，后续需要的之后再继续反馈，感谢
