### ISSUE TITLE
想问下LDAP同步要怎么设置，测试通过但无法获取到用户

### ISSUE THREAD

**Issue by ChangJieWuAi** [lxerxa/actionview#235]
目录名和Base DN填的是一样的，请问是哪里填错了吗？部署是centos7.9+nginx
![aview1](https://user-images.githubusercontent.com/70933212/215649531-3cd9968d-f416-4569-8b72-b666beceef3f.png)
![aview2](https://user-images.githubusercontent.com/70933212/215649537-ec678318-5b9b-406b-a481-44ecbf359c1d.png)
![aview3](https://user-images.githubusercontent.com/70933212/215649538-57962d66-b095-44dd-af3c-6ec388420ead.png)

**Comment by kingboy82** [comment]
同步的AD做的设置，供参考

1. 服务器
目录名：随意起名
主机名：你的服务器IP
端口：389
加密：无
用户名：用户的distinguishedName
密码：按实际输入

2. DN：
Base DN：用户所在OU的distinguishedName
其他不填

3. 用户
对象类：person
对象过滤：(objectclass=user)
用户名属性：description
邮箱属性：mail

4. 用户组：未设置
5. 组成员：未设置

**Comment by ChangJieWuAi** [comment]
> 同步的AD做的设置，供参考
> 
> 1. 服务器
>    目录名：随意起名
>    主机名：你的服务器IP
>    端口：389
>    加密：无
>    用户名：用户的distinguishedName
>    密码：按实际输入
> 2. DN：
>    Base DN：用户所在OU的distinguishedName
>    其他不填
> 3. 用户
>    对象类：person
>    对象过滤：(objectclass=user)
>    用户名属性：description
>    邮箱属性：mail
> 4. 用户组：未设置
> 5. 组成员：未设置

谢谢，已经同步成功了
