### ISSUE TITLE
点击问题以后一片空白

### ISSUE THREAD

**Issue by pengjieran** [lxerxa/actionview#24]
在Centos7中新安装的，点击问题的时候会出现这个错误，也无法添加，查看问题。
![default](https://user-images.githubusercontent.com/6761687/45595311-33ee5080-b9dc-11e8-8e5c-471ffb2f18eb.png)

**Comment by lxerxa** [comment]
清除缓存或强制刷新页面试试看。

**Comment by pengjieran** [comment]
好了，缓存清了就行。
