### ISSUE TITLE
字段配置无法绑定数据表字段

### ISSUE THREAD

**Issue by pertghost** [lxerxa/actionview#25]
能否开放给用户选择将字段的值绑定到数据库表的字段，并且可以选择是否可以编辑？

这样类似 实际开始时间、实际完成时间、实际关闭时间 都可以通过配置实现了

**Comment by lxerxa** [comment]
没太看明白您的意思？

**Comment by pertghost** [comment]
配置管理-字段-新建字段   只有类型可选  不能选择数据源  
能否绑定数据源？ 也就是数据库表的字段

**Comment by lxerxa** [comment]
抱歉，暂未支持

**Comment by cooper2006** [comment]
这个问题是否列到开发计划中，jira上有类似的插件。pcf
