### ISSUE TITLE
问题描述 目前貌似不支持富文本或者mardown，推荐支持

### ISSUE THREAD

**Issue by xiweicheng** [lxerxa/actionview#26]

**Comment by lxerxa** [comment]
暂未支持。

**Comment by dbskccc** [comment]
markdown现在还真用得不少，是应该争取支持

**Comment by lxerxa** [comment]
一般系统描述问题是非机构化的，只有标题和详细描述两个字段，这要求描述字段有足够强大功能来表述清楚内容，而actionview问题属性是结构化的，所以我认为描述字段没必要支持md。不过wiki模块会支持的，已进入测试阶段。

**Comment by lxerxa** [comment]
这次新版本发布后，不少用户提到了，希望在描述文本框里能支持图像的复制上传，争取在下个版本先支持了这个，至于Markdown可以再考虑下。

**Comment by lxerxa** [comment]
新版本已支持。
