### ISSUE TITLE
部署只能在根域上？能加context path吗？

### ISSUE THREAD

**Issue by rockkratos** [lxerxa/actionview#28]
通过docker部署，只能通过访问根path，是否可以添加类似java的context path？

例：
http://localhost:8080/ 可以打开系统，

是否可以变为http://localhost:8080/{自定义path}/来访问？

**Comment by lxerxa** [comment]
好像不可以，可考虑建子域名。

**Comment by lxerxa99** [comment]
争取在下个小版本发布是支持了，请关注。

**Comment by lxerxa** [comment]
争取在下个小版本发布时支持了，请关注。
