### ISSUE TITLE
该项目未定义看板

### ISSUE THREAD

**Issue by feilh** [lxerxa/actionview#35]
看板如何设置操作？

**Comment by lxerxa** [comment]
请参照：
![image](https://user-images.githubusercontent.com/5182909/54655892-88df6080-4afe-11e9-86d0-ed25f7f1b044.png)

**Comment by feilh** [comment]
> 请参照：
> ![图片](https://user-images.githubusercontent.com/5182909/54655892-88df6080-4afe-11e9-86d0-ed25f7f1b044.png)

![image](https://user-images.githubusercontent.com/48703070/54660446-73276680-4b11-11e9-8a04-da0c32c2b83d.png)

**Comment by lxerxa** [comment]
当前用户是否拥有管理项目权限？

**Comment by feilh** [comment]
好了，谢谢
