### ISSUE TITLE
部署完以后网站还是打不开？

### ISSUE THREAD

**Issue by iosmall** [lxerxa/actionview#36]
{"ecode":-99999,"emsg":"Type error: Argument 1 passed to Illuminate\\Cookie\\Middleware\\EncryptCookies::encrypt() must be an instance of Symfony\\Component\\HttpFoundation\\Response, array given, called in \/www\/wwwroot\/actionview\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Middleware\/EncryptCookies.php on line 59"}
部署完以后网站还是打不开？  折腾了几天了还是没搞定，不知道问题出在哪！

**Comment by lxerxa** [comment]
部署环境是？是否按照wiki上的步骤安装的？是否执行config.sh？

**Comment by iosmall** [comment]
php7.2.1.6-Nginx 1.15.9-MySQL 5.6.43-MongoDB 4.0.5- wiki按照step 3步骤开始部署！

**Comment by lxerxa** [comment]
不太好定位错误，好像是storage目录没有写入权限？

**Comment by iosmall** [comment]
`[root@i actionview]# composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 40 installs, 0 updates, 0 removals
  - Installing vlucas/phpdotenv (v2.3.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.2.0): Loading from cache
  - Installing symfony/var-dumper (v3.0.9): Loading from cache
  - Installing symfony/translation (v3.0.9): Loading from cache
  - Installing symfony/routing (v3.0.9): Loading from 

> cache

  - Installing symfony/process (v3.0.9): Loading from cache
  - Installing symfony/polyfill-util (v1.2.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.2.0): Loading from cache
  - Installing symfony/http-foundation (v3.0.9): Loading from cache
  - Installing symfony/event-dispatcher (v3.1.3): Loading from cache
  - Installing psr/log (1.0.0): Loading from cache
  - Installing symfony/debug (v3.0.9): Loading from cache
  - Installing symfony/http-kernel (v3.0.9): Loading from cache
  - Installing symfony/finder (v3.0.9): Loading from cache
  - Installing symfony/console (v3.0.9): Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.3): Loading from cache
  - Installing nikic/php-parser (v2.1.0): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing psy/psysh (v0.7.2): Loading from cache
  - Installing paragonie/random_compat (v1.4.1): Loading from cache
  - Installing nesbot/carbon (1.21.0): Loading from cache
  - Installing mtdowling/cron-expression (v1.1.0): Loading from cache
  - Installing monolog/monolog (1.20.0): Loading from cache
  - Installing league/flysystem (1.0.25): Loading from cache
  - Installing jeremeamia/superclosure (2.2.0): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing classpreloader/classpreloader (3.0.0): Loading from cache
  - Installing laravel/framework (5.2.41): Loading from cache
  - Installing adldap2/adldap2 (v8.1.5): Loading from cache
  - Installing cartalyst/support (v1.2.0): Loading from cache
  - Installing cartalyst/sentinel (v2.0.12): Loading from cache
  - Installing chumper/zipper (v1.0.2): Loading from cache
  - Installing mongodb/mongodb (1.0.2): Loading from cache
  - Installing jenssegers/mongodb (v3.0.2): Loading from cache
  - Installing symfony/css-selector (v3.0.9): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Loading from cache
  - Installing phpoffice/phpexcel (1.8.1): Loading from cache
  - Installing maatwebsite/excel (2.1.10): Loading from cache
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> composer dump-autoload --no-dev --optimize
Generated optimized autoload files containing 2147 classes
[root@i actionview]# sh config.sh
configure starting...
configure complete.
`

**Comment by iosmall** [comment]
storage目录 777权限！因为目前这个问题，我实在搞不懂了，光配置环境和扩展都搞了好几天，本身也没什么技术！

**Comment by iosmall** [comment]
是不是nginx的伪静态问题？

**Comment by iosmall** [comment]
`# php -m
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libxml
mbstring
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
swoole
sysvsem
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
zip
zlib

[Zend Modules]
`

**Comment by iosmall** [comment]
我再用另外一台服务器 全部初始化部署环境试试，看看还是不是一样的错误！

**Comment by lxerxa** [comment]
centos?ubuntu?

**Comment by iosmall** [comment]
centos

**Comment by iosmall** [comment]
centos7.6 x64

**Comment by iosmall** [comment]
CentOS Linux 7.6.1810 (Core)-php7.2.1.6-Nginx 1.15.9-MySQL 5.6.43-MongoDB 4.0.5

**Comment by lxerxa** [comment]
mongodb确认没问题吧？客户端能连接上吗？

**Comment by iosmall** [comment]
`2019-03-23T16:45:25.348+0800 I ACCESS   [conn4] Successfully authenticated as principal xxxddd on xxxddd
2019-03-23T21:55:58.600+0800 I NETWORK  [listener] connection accepted from 127.0.0.1:46778 #5 (3 connections now open)
2019-03-23T21:55:58.601+0800 I NETWORK  [conn5] received client metadata from 127.0.0.1:46778 conn5: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.5" }, os: { type: "Linux", name: "CentOS Linux release 7.6.1810 (Core) ", architecture: "x86_64", version: "Kernel 3.10.0-957.1.3.el7.x86_64" } }
2019-03-23T21:55:58.610+0800 I NETWORK  [conn5] end connection 127.0.0.1:46778 (2 connections now open)`

**Comment by iosmall** [comment]
![Uploading QQ截图20190323225028.png…]()
mongodb 按道理是没问题，我看数据库都有数据写进去，我用的是宝塔控制面板装的mongodb！
`
数据库名称 | 数据大小 | 操作
-- | -- | --
admin | 160.00 KB | 
config | 60.00 KB | 
local | 64.00 KB | 
xxxddd | 684.00 KB

`

**Comment by lxerxa** [comment]
实在不行，方便的话我可以帮你调试下。

**Comment by iosmall** [comment]
我添加了您官方的那个QQ！！！

**Comment by enterococcus** [comment]
類似的問題發生在GCP上的VM
使用 Centos 7 & Nginx 腳本
到 Step 5
访问系统: http://xxx.xxx.xxx.xxx, 管理员登录: user: admin@action.view, password: actionview
mongodb 可以查找到 admin@action.view, 連接DB也正常. 
首頁可以出現，但是就是通過帳號密碼驗證及登入網站.
請問有建議查修方式嗎？

**Comment by limuzi001** [comment]
@enterococcus 我也有类似的问题，您是怎么解决的呢？输入用户名密码就没反应了。

> 類似的問題發生在GCP上的VM
> 使用 Centos 7 & Nginx 腳本
> 到 Step 5
> 访问系统: http://xxx.xxx.xxx.xxx, 管理员登录: user: [admin@action.view](mailto:admin@action.view), password: actionview
> mongodb 連接DB正常，可以查找到 [admin@action.view](mailto:admin@action.view)這筆資料,.
> 首頁可以出現，但是就是通過帳號密碼驗證及登入網站.
> 請問有建議查修方式嗎？

**Comment by lxerxa** [comment]
@limuzi001 fpm是否正常启动？是否和nginx正常通信？DB是否安装成功？

**Comment by lxerxa** [comment]
@limuzi001 是否安装此目录下：
![image](https://user-images.githubusercontent.com/5182909/59107276-d71c3700-896a-11e9-813a-16f1b1e3234d.png)

**Comment by chenyang351** [comment]
@lxerxa 我也遇到相同问题，完全按照文档进行部署，可以确定mongodb连接及数据正常，nginx配置也无问题

**Comment by leirhy** [comment]
遇到了一样的问题，后面在测试环境重装了一遍解决了，生产环境按一样的方法重建不行，好坑……
