### ISSUE TITLE
关于文档目录打包下载，文件名不能使用中文

### ISSUE THREAD

**Issue by applehuaer** [lxerxa/actionview#38]
- 相关功能：

        项目中的文档下载功能

- 问题描述：

        中文文件直接可以下载，但是下载某个目录，当这个目录中包含使用中文名的文件时，zip打包时会跳过这个文件，如果文件目录中只有这一个文件，那么下载失败。

- 尝试解决：
1. 我到actionview的官网试过了，官网可以上传中文文件并下载，然后我使用docker的方式重新搭建了一遍，还是不行。

2. 配置docker环境的语言支持，仍然没有解决问题。
      

> 
root@5660fadce1f4:/var/www/actionview# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

        不知道是不是需要额外的配置呢？

**Comment by lxerxa** [comment]
locale -a
看下有没有zh_CN.utf8？
没有的话可能需要安装中文包了。

**Comment by applehuaer** [comment]
没有。。。

**Comment by applehuaer** [comment]
root@5660fadce1f4:/var/www/actionview# locale -a
C
C.UTF-8
POSIX
        谢谢大佬，我现在试试：）

**Comment by applehuaer** [comment]
谢谢大佬，我安装好zh_CN.utf8之后问题解决了。
