### ISSUE TITLE
Docker环境下如何迁移数据？

### ISSUE THREAD

**Issue by jxwuqingyan** [lxerxa/actionview#39]
环境：CentOS7.2  Docker
请问如何迁移数据库？

**Comment by lxerxa** [comment]
从哪里迁到哪里？docker安装的话，db数据文件都在 data/db 下。

**Comment by jxwuqingyan** [comment]
就是从一台服务器迁移到另一台服务器，只要拷贝data/db下的文件  然后重新运行 docker-compose就行吗？

**Comment by lxerxa** [comment]
是这样的。

**Comment by jxwuqingyan** [comment]
> 是这样的。

那如果我想把db的端口映射出来是不是修改docker-compose.yml 
expose:
      - 27017
改为
 ports:
      - 自定义端口:27017

然后docker-compose build 再docker-compose up -d这样呢？还是有其他操作

**Comment by lxerxa** [comment]
db容器27017已经expose了吧，docker-compose build可能不行，没写那个命令，可以单独build db的dockerfile.

**Comment by jxwuqingyan** [comment]
> db容器27017已经expose了吧，docker-compose build可能不行，没写那个命令，可以单独build db的dockerfile.

嗯  我是想把db容器的27017映射到宿主机的一个端口，然后外部通过宿主机IP 去连DB

**Comment by lxerxa** [comment]
了解，可以按照你的方式修改docker-compose.yml，然后再docker-compose up，不需要docker-compose build.

**Comment by jxwuqingyan** [comment]
> 了解，可以按照你的方式修改docker-compose.yml，然后再docker-compose up，不需要docker-compose build.

好的 非常感谢~~

**Comment by jxwuqingyan** [comment]
不好意思  再咨询下  默认的mongo数据库名 用户名 密码是什么

**Comment by lxerxa** [comment]
USER=${MONGODB_USERNAME:-actionview}
PASS=${MONGODB_PASSWORD:-secret}
DB=${MONGODB_DBNAME:-actionviewdb}

**Comment by jxwuqingyan** [comment]
> USER=${MONGODB_USERNAME:-actionview}
> PASS=${MONGODB_PASSWORD:-secret}
> DB=${MONGODB_DBNAME:-actionviewdb}

OK
