### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by cnjxps** [lxerxa/actionview#4]
无法连接mongodb，是否有相关文档可以参考。

**Comment by lxerxa** [comment]
1. 确认mongodb是否安装成功？可以用命令行连接试试看，如：mongo 127.0.0.1/dbname -uxxx -pxxx
2. 是否安装了php-mongodb的扩展，例如ubuntu: apt-get install php-mongodb

**Comment by cnjxps** [comment]
mongo和php-mongo都装好了，web能打开，能登录，但是好多session，api都提示404.

**Comment by cnjxps** [comment]
database.php文件也已经修改了相关的用户名和密码，dbnamem

**Comment by lxerxa** [comment]
1. 是否执行config.sh脚本？
2. Apache的配置文件是否添加如下代码：
        <Directory /var/www/actionview/public>
            Options FollowSymLinks
            Order deny,allow
            AllowOverride All
        </Directory>

**Comment by cnjxps** [comment]
Hi lxerxa:

     谢谢支持，刚刚检查了下，是没有修改.env下的数据库用户名密码，没有在httpd增加htaccess配置，添加修改以后，重新执行了config.sh,现在无法登陆，提示用户名失败，是不是数据库配置的问题？

**Comment by lxerxa** [comment]
是否执行数据库初始化脚本，
mongorestore -h 127.0.0.1 -u username -p secret -d dbname --drop ./dbdata

**Comment by cnjxps** [comment]
这个执行了，在mongo里面能看到表，内容都有。

**Comment by lxerxa** [comment]
admin@action.view 使用这个账号登录的吗？

**Comment by cnjxps** [comment]
是的，我再重新部署下试试看。

**Comment by cnjxps** [comment]
总感觉php没有执行链接到mongo的动作，检查了php-mongo有load进去的，在mongo的log里面没有任何链接成功或者失败的log。

**Comment by lxerxa** [comment]
谢谢整理！
**2.修改了config/database.php，修改了db的用户名密码；**
如果第3条配置了，第二条就不需要做任何修改的，因为先读取的是环境变量。

**Comment by cnjxps** [comment]
已经修改，还是提示密码错误，有什么方法可以判断php链接数据库是否正常，能看到哪里有问题么。

**Comment by lxerxa** [comment]
能看到接口的返回值是什么吗？

**Comment by cnjxps** [comment]
服务器返回的是PHP文件，看起来是apache问题，我在看现在。

**Comment by cnjxps** [comment]
重新安装了apache和php相关组件，现在能登陆成功，但是会秒返回，session和recent会出现505，持续检查环境中。

**Comment by cnjxps** [comment]
Hi lxerxa:

    我现在怀疑是我环境版本和您开发版本不一致导致，能否提供您这的apache，php，mongodb的具体版本呢，谢谢。

**Comment by lxerxa** [comment]
我觉的不是版本的问题，方便留下你的qq吗？

**Comment by cnjxps** [comment]
qq:376739304

**Comment by lxerxa** [comment]
整理了ubuntu安装步骤  
[ubuntun-Installation](https://github.com/lxerxa/actionview/wiki/Ubuntu-Installation)
