### ISSUE TITLE
上传附件大小有大小限制吗？

### ISSUE THREAD

**Issue by lxlw1320** [lxerxa/actionview#40]
nginx也没限制，但是大于2m的文件传上去就没了。

**Comment by lxerxa** [comment]
是怎么安装的？

**Comment by lxlw1320** [comment]
用docker装的

**Comment by lxerxa** [comment]
可能镜像里做大小限制的处理，记下这个问题了。等待发布新的web镜像然后升级。

**Comment by lxlw1320** [comment]
好的，有办法自己修改吗

**Comment by lxerxa** [comment]
修改web dockerfile, 重新build web镜像。

**Comment by lxlw1320** [comment]
不知道要改哪些，最近会发布新的吗

**Comment by lxerxa** [comment]
想和下个版本一起发布，可能要等一段时间吧。

**Comment by lxlw1320** [comment]
有办法通过修改参数暂时解决这个问题不

**Comment by lxerxa** [comment]
不太好处理，需要修改container里的配置文件。

**Comment by lxlw1320** [comment]
= =好吧，下个版本有预计大概啥时候出来不

**Comment by lxerxa99** [comment]
下个版本功能较多，预计一个月左右吧。

**Comment by lxerxa** [comment]
下个版本功能较多，预计一个月左右吧。

**Comment by lxerxa** [comment]
新版本已发布，docker镜像也同步发布，请知晓。

**Comment by lxlw1320** [comment]
谢谢通知，我马上更新下试试
