### ISSUE TITLE
CentOS Installation(Nginx) 安装依赖时失败

### ISSUE THREAD

**Issue by bole2u** [lxerxa/actionview#43]
在虚拟机centos上，执行第3步的composer install --no-dev的时候，失败报错
Your requirements could not be resolved to an installable set of packages.
 Problem 1
    - adldap2/adldap2 v8.1.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap2/adldap2 v8.1.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for adldap2/adldap2 v8.1.5 -> satisfiable by adldap2/adldap2[v8.1.5].
  To enable extensions, verify that they are enabled in your .ini files:
    - /www/server/php/70/etc/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

换了我们的阿里云服务器（centos）也是这样
Problem 1
    - Installation request for adldap2/adldap2 v8.1.5 -> satisfiable by adldap2/adldap2[v8.1.5].
    - adldap2/adldap2 v8.1.5 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
  Problem 2
    - Installation request for mongodb/mongodb 1.0.2 -> satisfiable by mongodb/mongodb[1.0.2].
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
  Problem 3
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - jenssegers/mongodb v3.0.2 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.2].
    - Installation request for jenssegers/mongodb v3.0.2 -> satisfiable by jenssegers/mongodb[v3.0.2].
  To enable extensions, verify that they are enabled in your .ini files:
    - /www/server/php/71/etc/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
能帮忙分析下是什么原因吗？谢谢

**Comment by lxerxa** [comment]
应该 是 php-ldap没有安装成功，试着修改下这个组件的名字重新安装下。
![image](https://user-images.githubusercontent.com/5182909/59106519-32e5c080-8969-11e9-8584-5a439cbc9609.png)
