### ISSUE TITLE
安装完提示mongo版本不对？

### ISSUE THREAD

**Issue by tdWarren** [lxerxa/actionview#45]
这是提示信息，emsg: "Server at 127.0.0.1:27017 reports wire version 2, but this version of libmongoc requires at least 3 (MongoDB 3.0)
我是要装新版本的mongo还是做什么

**Comment by a1ading** [comment]
安装新版本的mongodb即可，我安装的mongodb3.4版本

**Comment by tdWarren** [comment]
> 安装新版本的mongodb即可，我安装的mongodb3.4版本

是的，我已经安装了，谢谢！
