### ISSUE TITLE
能否支持从Jira把数据导过来？

### ISSUE THREAD

**Issue by zhgypg** [lxerxa/actionview#47]
看了demo，感觉很不错。但是我们已经用了很久的Jira和谐版。  不知道能不能支持或者未来有没有计划实现从Jira导数据过来？

**Comment by lxerxa** [comment]
抱歉，暂未在开发计划里，不过将来有时间可以考虑。

**Comment by lxerxa** [comment]
最新版已支持excel的问题导入了。
