### ISSUE TITLE
部署完成无法登陆

### ISSUE THREAD

**Issue by zxb15589795** [lxerxa/actionview#49]
使用centos+nginx部署完成。页面正常显示，输入账号密码 user: admin@action.view, password: actionview无法登陆。提示“若非该系统用户，请联系系统管理员创建”

**Comment by lxerxa** [comment]
信息太少，不好定位问题。

**Comment by xiaoxun2536** [comment]
APP_ENV=local
APP_KEY=d966vMFAGt8LeRD6m6Opz35P0nHyDkKM
APP_DEBUG=false
APP_LOG_LEVEL=error
APP_LOG=daily

DB_HOST=127.0.0.1
DB_DATABASE=actionviewdb
DB_PORT=27017
DB_USERNAME=actionview
DB_PASSWORD=secret

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

#REDIS_HOST=127.0.0.1
#REDIS_PASSWORD=null
#REDIS_PORT=6379

#MAIL_DRIVER=smtp
#MAIL_HOST=smtp.126.com
#MAIL_PORT=465
#MAIL_USERNAME=xxx
#MAIL_PASSWORD=xxx
#MAIL_ENCRYPTION=ssl
#MAIL_ADDRESS=xxx@126.com
这是.env的配置文件  哪里需要修改吗？

**Comment by xiaoxun2536** [comment]
![QQ图片20190614100424](https://user-images.githubusercontent.com/51806699/59478442-d95f2380-8e8b-11e9-8cb3-79e8c41e0a14.png)

**Comment by sxke** [comment]
同样的问题

**Comment by lxerxa** [comment]
方便服务器地址发mail给我？

**Comment by xiaoxun2536** [comment]
服务器为内网地址，您访问不了，您需要我提供什么信息或日志我来截图好吗？

**Comment by lanbo-huang** [comment]
同样的问题，部署好之后。直接使用ttp://ip地址能进入登陆界面，但使用admin@action.view /actionview  登陆不了系统。使用http://ip/actionview 能进入http://ip/myproject

**Comment by lxerxa** [comment]
从现象看应该是后台接口访问出了问题，原因：1. nginx和fpm访问是否正常？2. 可能是mongodb的问题。

**Comment by lanbo-huang** [comment]
应该是mongodb的问题，今天登陆的时候看了一下错误日志。但我不知道怎么解决，悲催。
[Tue Jun 18 11:31:07.625333 2019] [:error] [pid 6710] [client 192.168.112.1:54990] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/actionview/storage/logs/laravel-2019-06-18.log" could not be opened: failed to open stream: Permission denied in /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#4 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#5 /var/www/actionview/vendor/la in /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107, referer: http://192.168.112.134/
[Tue Jun 18 11:31:07.625875 2019] [:error] [pid 6710] [client 192.168.112.1:54990] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/actionview/storage/logs/laravel-2019-06-18.log" could not be opened: failed to open stream: Permission denied in /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/actionview/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/actionview/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\Fat in /var/www/actionview/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107, referer: http://192.168.112.134/

**Comment by lxerxa** [comment]
@lanbo-huang 看日志好像是权限的问题。是否执行 config.sh。

**Comment by lanbo-huang** [comment]
执行了的。都打印了 complete
configure starting...
configure complete.

**Comment by lxerxa** [comment]
@lanbo-huang 实际目录（var/www/actionview/storage/）看下，是否真的有写权限？

**Comment by shilover** [comment]
相同问题+1    我的storage下权限777

**Comment by lxerxa** [comment]
关闭SELinux应该就可以了，大家可试试。

**Comment by shilover** [comment]
@lxerxa 我是部署完就关了的，因为不关没有办法把网页根目录改到actionview里😂


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by lxerxa** [comment]
@shilover 登录api还是500错误吗？

**Comment by lanbo-huang** [comment]
关闭了SElinux ，不报错了，但使用admin@action.view/actionview 任然登不进去，api也是200
192.168.112.1 - - [19/Jun/2019:09:42:56 +0800] "POST /api/session HTTP/1.1" 200 135 "http://192.168.112.140/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"
192.168.112.1 - - [19/Jun/2019:09:42:56 +0800] "POST /api/session HTTP/1.1" 200 135 "http://192.168.112.140/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36"

**Comment by lxerxa99** [comment]
@lanbo-huang /api/session返回内容是什么？f12看下。

**Comment by lanbo-huang** [comment]
Mongdb 不匹配的原因
![mo](https://user-images.githubusercontent.com/45221102/59731525-0a1ece80-9279-11e9-89eb-b5172b14f004.png)

**Comment by lxerxa** [comment]
这个问题升级下 mongodb就可以了。参考：https://www.cnblogs.com/layezi/p/7290082.html

**Comment by lxerxa** [comment]
参考问题 #45

**Comment by shilover** [comment]
搞定 thx

**Comment by shilover** [comment]
1、sudo service mongod stop  关闭数据库
2、sudo yum erase mongodb mongodb-server  删除数据库
3、删除数据和log（这一步应该是可选的，因为我是空数据，就直接全删了）
4、然后按照https://www.cnblogs.com/layezi/p/7290082.html 重新安装3.4版
6、sudo service mongod start 启动数据库
7、再按照av的安装说明重新创建用户（没进行第三步应该不需要做这步，没经过测试不确定）
8、重新创建表格（没进行第三步应该不需要做这步，没经过测试不确定）

**Comment by lanbo-huang** [comment]
> 参考问题 #45
感谢，终于搞定！
