### ISSUE TITLE
表示不做php的，搭环境都好痛苦，建议写个具体的wiki，或者搭个docker images提供下载

### ISSUE THREAD

**Issue by Epic1028** [lxerxa/actionview#5]

**Comment by lxerxa** [comment]
ubuntu 和 centos的正在整理中，可能最近会发布的，请稍等。另外，docker image 过段时间也会提供。

**Comment by cnjxps** [comment]
现在遇到什么问题了呢，说下你现在的进度。

**Comment by Epic1028** [comment]
到目前是按照步骤导入数据库失败，修改mongo配置后成功，不知道数据库的配置是不是都在
.env里设置。然后登入后是空的，只有个人设置，无法使用是吗？注册也是提示试用版没法用。qq也联系不上。

**Comment by Epic1028** [comment]
@lxerxa 上午有空帮我联调下吗

**Comment by lxerxa** [comment]
整理了Ubuntu安装步骤:  
[ubuntu-Installation](https://github.com/lxerxa/actionview/wiki/Ubuntu-Installation)
