### ISSUE TITLE
不支持绑定手机吗？

### ISSUE THREAD

**Issue by xiaoxun2536** [lxerxa/actionview#50]
个人设置里点帮点手机号显示暂时不支持此功能。 还有 我是docker安装的 如何进入数据库查看信息

**Comment by lxerxa** [comment]
支持手机需要短信网关的，暂时没有，所以不支持。看db container数据，请研究docker，我也不是很了解。

**Comment by xiaoxun2536** [comment]
进入mongo的容器看过了  到库里查看show dbs和show users都报错了 不知道怎么查数据  别的容器里都没有mongo
