### ISSUE TITLE
actionview的日志文件在哪？

### ISSUE THREAD

**Issue by jitre** [lxerxa/actionview#51]
我配置完邮件服务器之后显示发送邮件事情，我想找下log定位一下问题，但不知道具体的位置

**Comment by jitre** [comment]
docker的版本

**Comment by lxerxa** [comment]
docker日志不太好看，研究下是哪里配置错了，本身功能是没问题的。

**Comment by jitre** [comment]
![image](https://user-images.githubusercontent.com/16094160/60088582-7ca81680-9771-11e9-8761-62390f6fefdc.png)
这个是我的邮箱配置，用的企业微信的邮箱服务器，服务器开了465端口的入和出
