### ISSUE TITLE
工时统计显示不正确

### ISSUE THREAD

**Issue by zhang0ZGC** [lxerxa/actionview#54]
![mmexport1562248642527](https://user-images.githubusercontent.com/10346399/60671945-d8c41680-9ea6-11e9-8a7c-e28861bfb0f6.jpg)
![mmexport1562248632985](https://user-images.githubusercontent.com/10346399/60671970-e1b4e800-9ea6-11e9-821c-6669a7db3b9b.jpg)

多次提交工作记录，在列表中的耗费时间只显示了最后一条的用时，但是剩余时间算的又是对的， 完成度好像也是按最后一条加的

**Comment by lxerxa** [comment]
是显示的问题，会尽快修复的。谢谢！

**Comment by lxerxa** [comment]
@zhang0ZGC 已修复，如果不是docker安装的话，可直接pull代码。

**Comment by zhang0ZGC** [comment]
@lxerxa 巧了……docker安装的话咋升级？

**Comment by lxerxa** [comment]
还没有build新的web镜像，只能自己build或等待新镜像发布，到时候再通知您吧。

**Comment by zhang0ZGC** [comment]
> 还没有build新的web镜像，只能自己build或等待新镜像发布，到时候再通知您吧。

您好，我可以现在docker里面把最新代码直接拉下来用么？ :smile:

**Comment by lxerxa** [comment]
原则上是可以的，没试过。

**Comment by zhang0ZGC** [comment]
谢谢了，在docker里面直接执行`git pull`从gitee拉到了最新代码:smile:
