### ISSUE TITLE
docker服务重启后，docker_actinviewweb_1无法启动

### ISSUE THREAD

**Issue by wangshaojie11** [lxerxa/actionview#57]
docker服务重启后，docker_actinviewweb_1无法启动，docker  logs 报错   AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
httpd (pid 1) already running

请问需要什么配置才能正常启动？

**Comment by lxerxa** [comment]
是不是端口被其他服务占用了？

**Comment by wangshaojie11** [comment]
你好！


   端口没有被占用，这个服务docker_actinviewweb_1应该走8080端口。

请问还有其他的可能吗？


------------------ 原始邮件 ------------------
发件人: "lxerxa"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 中午11:34
收件人: "lxerxa/actionview"<actionview@noreply.github.com>;
抄送: "王少杰"<515188209@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lxerxa/actionview] docker服务重启后，docker_actinviewweb_1无法启动 (#57)




是不是端口被其他服务占用了？

**Comment by lxerxa** [comment]
先down，再up，试过吗？

**Comment by wangshaojie11** [comment]
你好！


   不好意思，上午有其他的事情了，没有及时回复。


刚down 掉，重新启动了
docker run -d -p 8080:80 -v /etc/localtime:/etc/localtime lxerxa/actionview:latest
现在已经可以启动了，但是无法登录，报
{"ecode":13053,"emsg":"No suitable servers found (`serverselectiontryonce` set): [Failed connecting to 'db:27017': php_network_getaddresses: getaddrinfo failed: Name or service not known]"}
这应该是无法连接数据库，但是

lxerxa/actionviewdb:latest 在正常的运行，是我启动lxerxa/actionview:latest的时候 需要指定数据库的连接地址吗？



------------------ 原始邮件 ------------------
发件人: "lxerxa"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 中午11:43
收件人: "lxerxa/actionview"<actionview@noreply.github.com>;
抄送: "王少杰"<515188209@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lxerxa/actionview] docker服务重启后，docker_actinviewweb_1无法启动 (#57)




先down，再up，试过吗？

**Comment by lxerxa** [comment]
为什么要单独run呢？docker-compose up?

**Comment by wangshaojie11** [comment]
你好！


    docker-compose up 果然可以！感谢指导 




------------------ 原始邮件 ------------------
发件人: "lxerxa"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 晚上6:04
收件人: "lxerxa/actionview"<actionview@noreply.github.com>;
抄送: "王少杰"<515188209@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lxerxa/actionview] docker服务重启后，docker_actinviewweb_1无法启动 (#57)




为什么要单独run呢？docker-compose up?
