### ISSUE TITLE
建议添加支持问题的 Excel导入功能，目前好像只支持excel导出

### ISSUE THREAD

**Issue by tanshion** [lxerxa/actionview#58]
建议添加支持问题的 Excel导入功能

**Comment by lxerxa** [comment]
有好几个用户提了此需求，争取下个版本支持。

**Comment by zhongw** [comment]
@lxerxa 你好，
感谢提供如此优秀的软件。
我已经安装并结束了试用，目前就缺数据导入了（redmine），能否请问一下，支持excel导入问题的功能大概在什么时候可以发布呢？

**Comment by lxerxa** [comment]
@zhongw  抱歉，开发Actionview主要是利用下班后或周末时间，所以无法给出一个准确的时间点，只能说会尽快完成1.8.4的发布，大概 3～4周的样子吧。

**Comment by zhongw** [comment]
谢谢。

**Comment by lxerxa** [comment]
新版已支持excel的导入了。
