### ISSUE TITLE
Issue disappears after setting up version

### ISSUE THREAD

**Issue by yort-feng** [lxerxa/actionview#59]
kanban模式，当设置完问题的版本后，该问题不再显示在看板里，在问题列表里还可见。

**Comment by lxerxa** [comment]
就是这个样子的。

**Comment by yort-feng** [comment]
哈？为啥会这样设计？

**Comment by lxerxa** [comment]
用kanban模式管理任务的话，原则上解决版本应该通过看板的发布功能来设置。
![image](https://user-images.githubusercontent.com/5182909/61791120-ac6b3c80-ae4b-11e9-887d-c0dc4a52c5f6.png)

**Comment by yort-feng** [comment]
出发点不太一样，我是希望在看板也能看到任务的一些关键信息，比如版本、预计结束时间和标签，信息更直观方便做决策，不然都需要点开来看~

**Comment by lxerxa** [comment]
看板显示哪些字段可通过设置看板显示字段来实现，争取下个版本完善这块功能，但是解决版本只能这样了。

**Comment by yort-feng** [comment]
好的！弱弱的问下，下个版本上线日期是什么时候？

**Comment by lxerxa** [comment]
预计两周内。
