### ISSUE TITLE
管理员登陆时提示系统错误

### ISSUE THREAD

**Issue by pop1wlf** [lxerxa/actionview#6]
使用如下教程里提供的用户名密码，登陆时提示系统错误。
管理员登录：user: admin@action.view, password: actionview

**Comment by lxerxa** [comment]
1.  是否执行了配置脚本 sh config.sh? 是否导入初始化数据?
2. 登陆时/api/session接口返回了什么？apache的rewrite是否启用？

**Comment by fanjie1225** [comment]
您好，使用Docker 安装第二种方法Docker Image，登录时也提示系统错误，是什么问题呢？

**Comment by lxerxa** [comment]
@fanjie1225 第一种方法有试过吗？

**Comment by fanjie1225** [comment]
您好，第一种方法可以，谢谢

**Comment by lxerxa** [comment]
第二种可能哪里配置有点问题，等有时间我测试下，不好意思。

**Comment by fanjie1225** [comment]
在请教您一个问题，docker-compose up -d 之后怎么看输出的日志信息呢，没找到在哪看

**Comment by fanjie1225** [comment]
目前这个版本不支持自定义更换头像功能是吧

**Comment by lxerxa** [comment]
是支持头像更换的，是不是docker映射路径权限的有问题

**Comment by lxerxa** [comment]
可能是管理员不支持头像，普通用户是支持的。

**Comment by fanjie1225** [comment]
添加头像后显示不出来

**Comment by lxerxa** [comment]
这是一个问题，把docker/data的访问权限改成 777 就可以了

**Comment by fanjie1225** [comment]
ok ,可以了 ，太感谢了
