### ISSUE TITLE
重新分配经办人

### ISSUE THREAD

**Issue by gongxufan** [lxerxa/actionview#61]
编辑问题修改经办人，问题列表没有刷新，导致改了经办人还能操作该问题。

期望：刷新问题列表，否则还能编辑

**Comment by lxerxa** [comment]
问题列表的操作权限是和当前用户的项目权限相关的，和问题的经办人没有干系。

**Comment by gongxufan** [comment]
> 问题列表的操作权限是和当前用户的项目权限相关的，和问题的经办人没有干系。

比如我把问题批给别人，完了这个问题还我这呢。手动刷新才行

**Comment by lxerxa** [comment]
能否截个图，我这里看列表是自动刷新的。
