### ISSUE TITLE
问题列表页面显示列配置能支持统一配置吗

### ISSUE THREAD

**Issue by yort-feng** [lxerxa/actionview#62]
当前的情况是各账号配置的显示列互不影响，这个是不必要的，同项目的人，需要的信息肯定是一样的

我希望通过管理员配置后，各账号看到的结果都一样，其他账号不允许更改这个配置就好

**Comment by lxerxa** [comment]
说的有道理，基于项目的配置比基于个人的配置好像更实用？灵活性是不是会差一点？

**Comment by yort-feng** [comment]
这里灵活性的意义不大，我使用过挺多需求管理的工具，readmine、zentao、teambition、tapd等，哪怕是用excel，需求的表头都会是统一的，不用给大家太多选择😂

**Comment by lxerxa** [comment]
好的，下个版本支持。不过Jira可以用户自定义的。

**Comment by yort-feng** [comment]
赞！
