### ISSUE TITLE
docker install 无法连接数据库

### ISSUE THREAD

**Issue by leona0918** [lxerxa/actionview#65]
使用docker 安装，运行 docker-compose up命令后 log 信息如下：

_2019-08-05T15:22:23.698+0000 [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data 64-bit host=5c39f03233d9
db_1     | 2019-08-05T15:22:23.699+0000 [initandlisten] db version v2.6.10
db_1     | 2019-08-05T15:22:23.699+0000 [initandlisten] git version: nogitversion
db_1     | 2019-08-05T15:22:23.699+0000 [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
db_1     | 2019-08-05T15:22:23.699+0000 [initandlisten] build info: Linux lgw01-12 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 BOOST_LIB_VERSION=1_58
db_1     | 2019-08-05T15:22:23.699+0000 [initandlisten] allocator: tcmalloc
db_1     | 2019-08-05T15:22:23.699+0000 [initandlisten] options: { security: { authorization: "enabled" }, storage: { dbPath: "/data", smallFiles: true } }
db_1     | 2019-08-05T15:22:24.571+0000 [initandlisten] journal dir=/data/journal
db_1     | 2019-08-05T15:22:24.575+0000 [initandlisten] recover : no journal files present, no recovery needed
db_1     | 2019-08-05T15:22:24.764+0000 [initandlisten] ERROR:   mmap() failed for /data/local.ns len:16777216 errno:22 Invalid argument
db_1     | 2019-08-05T15:22:24.764+0000 [initandlisten] error couldn't open file /data/local.ns terminating
db_1     | 2019-08-05T15:22:24.764+0000 [initandlisten] dbexit:
db_1     | 2019-08-05T15:22:24.764+0000 [initandlisten] shutdown: going to close listening sockets...
db_1     | 2019-08-05T15:22:24.764+0000 [initandlisten] shutdown: going to flush diaglog...
db_1     | 2019-08-05T15:22:24.765+0000 [initandlisten] shutdown: going to close sockets...
db_1     | 2019-08-05T15:22:24.765+0000 [initandlisten] shutdown: waiting for fs preallocator...
db_1     | 2019-08-05T15:22:24.765+0000 [initandlisten] shutdown: lock for final commit...
db_1     | 2019-08-05T15:22:24.765+0000 [initandlisten] shutdown: final commit...
db_1     | 2019-08-05T15:22:24.765+0000 [initandlisten] shutdown: closing all files...
db_1     | 2019-08-05T15:22:24.765+0000 [initandlisten] closeAllFiles() finished
db_1     | 2019-08-05T15:22:24.765+0000 [initandlisten] journalCleanup...
db_1     | 2019-08-05T15:22:24.771+0000 [initandlisten] removeJournalFiles
db_1     | 2019-08-05T15:22:24.877+0000 [initandlisten] shutdown: removing fs lock...
db_1     | 2019-08-05T15:22:24.878+0000 [initandlisten] dbexit: really exiting now
cron_1   |  * Starting periodic command scheduler cron
cron_1   |    ...done.
docker_db_1 exited with code 45_

如何确定数据库正确连接？

**Comment by lxerxa** [comment]
应该是宿主主机机内存太小了。

**Comment by leona0918** [comment]
> 应该是宿主主机机内存太小了。

本地环境win10 64位，8G内存。应该不是内存小的原因吧

**Comment by leona0918** [comment]
我的主机环境是win10 enterprise, 安装了docer for windows10, 启动MongoDB 一直有问题，在网上看到一个说法：
**_需要使用-v参数来加载（mount）一个磁盘目录（volume）的时候，就会出现问题，至少我在MongoDB中使用-v参数来将MongoDB的数据文件映射到主机目录时，就会导致MongoDB无法正常启动。这个问题在Hyper-V出现之前，在Virtual Box时代就有，而且根据社区的讨论，似乎在Hyper-V的版本中也还是没有解决。详细信息可以参考这里：https://stackoverflow.com/questions/42756776/how-do-i-configure-mongo-to-run-in-docker-to-using-an-external-drive-on-windows。_**
现在切换到ubuntu
