### ISSUE TITLE
修改邮件发送代码不生效

### ISSUE THREAD

**Issue by Millkxuan** [lxerxa/actionview#66]
我想对邮件发送功能做点修改，但是在邮件代码中注释掉关键代码、甚至die掉代码之后，邮件依然能正常发送。而如果通过命令行手动执行邮件发送命令，则修改的代码是生效的。请问这是什么原因？是我忽略了什么地方嘛？

**Comment by Millkxuan** [comment]
用的docker

**Comment by lxerxa** [comment]
重启crond试试？

**Comment by lxerxa** [comment]
docker发送邮件代码在cron container里，没在web container。

**Comment by Millkxuan** [comment]
> docker发送邮件代码在cron container里，没在web container。
噢噢 了解了，谢谢！
