### ISSUE TITLE
建议优先级的默认选项名称可以修改，目前默认的只能调整顺序

### ISSUE THREAD

**Issue by tanshion** [lxerxa/actionview#67]
建议优先级的默认选项名称可以修改，这样可以灵活的根据公司管理需求定义名称，比如团队想用A，B ,C  ,D  统一定义需求和bug的优先级

![image](https://user-images.githubusercontent.com/9196558/63271131-0a186a80-c2cc-11e9-910d-df537924f0d2.png)

**Comment by lxerxa** [comment]
可以考虑。

**Comment by lxerxa** [comment]
新版本1.8.4内置优先级如果没有关联问题的话都可以删除了，然后定义自己想要的。

**Comment by tanshion** [comment]
你好，我更新1.8.4，内置优先级还是不能删除，只有自己添加的才可以删除和编辑
![image](https://user-images.githubusercontent.com/9196558/65370664-0773b100-dc8e-11e9-8189-65d0d3e73138.png)
![image](https://user-images.githubusercontent.com/9196558/65370666-10648280-dc8e-11e9-94c3-47f9cf2baab9.png)

**Comment by lxerxa** [comment]
不能删除是因为该优先级已被项目问题关联使用了。

**Comment by tanshion** [comment]
我是使用docker部署了一个全新的环境，没有项目问题的，还是不能删除，或许是docker部署方式有问题

**Comment by lxerxa** [comment]
是有点问题，已修复，可以获取最新的代码或最新的docker。

**Comment by tanshion** [comment]
已解决，完美
