### ISSUE TITLE
CentOS 7.4+apache部署后接口500错误

### ISSUE THREAD

**Issue by RichardHou307** [lxerxa/actionview#68]
已按指导执行全部步骤（除最后的cron配置），数据库初始化、config.sh都提示成功，使用IP能正常打开登录页面，但是进页面GET api/session接口报500错误，输入默认账号密码POST api/session接口也是同样的500错误，请问应该如何定位。

**Comment by lxerxa** [comment]
参照  #49 是否有帮助。

**Comment by RichardHou307** [comment]
> 参照 #49 是否有帮助。

搞定了，重装mongodb后遇到无法启动的问题，将mongod.log权限设为777后搞定，数据需要重新初始化。
