### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by maokuan** [lxerxa/actionview#7]
1.登录的时候 api/session接口 提示 {"ecode":0,"emsg":"Call to a member function compileSelect() on null"}
2.账号密码是你提供的（admin@action.view   actionview）
3.我的环境是windows+nginx+mongodb
4.查看laravel的log，我复制的一部分([2018-02-02 20:20:03] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function send() on array in E:\WWW\actionview\public\index.php:60
Stack trace:
#0 {main}  
[2018-02-02 20:20:03] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Error: Call to a member function send() on array in E:\WWW\actionview\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:107
Stack trace:
#0 E:\WWW\actionview\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(84): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in E:\WWW\actionview\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php:107
Stack trace:
#0 {main}  
[2018-02-02 20:20:08] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function compileSelect() on null in E:\WWW\actionview\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1514
Stack trace:
#0 E:\WWW\actionview\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1583): Illuminate\Database\Query\Builder->toSql()
#1 E:\WWW\actionview\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1569): Illuminate\Database\Query\Builder->runSelect()
#2 E:\WWW\actionview\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(625): Illuminate\Database\Query\Builder->get(Array))    感觉是mongodb配置的问题，但是我也初始化了数据库，也在actionviewdb里面创建用户actionview和密码secret,你能帮我看下r日志吗

**Comment by lxerxa** [comment]
config.sh是否执行，那个只是针对linux系统的，windows可能需要参照config.sh手动修改一些文件。

**Comment by maokuan** [comment]
把config.sh文件改成.bat的格式在windows下执行了,,,,,但是还是报上面的错误，手动不知道怎么改— —

**Comment by lxerxa** [comment]
几个替换脚本命令，仔细看下应该能明白。

**Comment by maokuan** [comment]
好了，下载了git然后把shell脚本执行了，现在可以登录了，谢谢了啊
