### ISSUE TITLE
如何删除问题

### ISSUE THREAD

**Issue by sxd1140** [lxerxa/actionview#73]
有一些问题是更改工作流之前创建的,找不到删除的地方

**Comment by lxerxa** [comment]
用户有删除问题的权限就可以删除的。

**Comment by lxerxa** [comment]
可以通过重置状态功能绑定新的工作流。

**Comment by sxd1140** [comment]
现在加了删除和重置权限就可以了.
开发人员组默认没有删除权限可以理解, 但是管理员都无法删除,和我认为的`管理员可以干任何事`的思维冲突了 哈.

**Comment by lxerxa** [comment]
权责分明还是好的。
