### ISSUE TITLE
服务器重启后接口报500错误

### ISSUE THREAD

**Issue by RichardHou307** [lxerxa/actionview#76]
centos+apache，正常运行一个月，国庆下电服务器后，业务无法恢复，接口报500错误，shell查看mongodb是正常的，备份数据后，重新执行了config.sh和db的初始化，问题依旧，也看不到报错信息。

**Comment by RichardHou307** [comment]
selinux也关了

**Comment by lxerxa** [comment]
不好定位，应该是系统的问题。

**Comment by RichardHou307** [comment]
重装了mongodb，重新clond了actionview，接口仍然500错误，有办法看到日志吗

**Comment by RichardHou307** [comment]
启动apache和访问登录页面时，mongodb的日志没有任何反应，感觉是actionview操作不到数据库，可能是什么原因导致的呢

**Comment by lxerxa** [comment]
是不是mongodb驱动版本的问题？

**Comment by lxerxa** [comment]
storage/logs 下有最新的日志可查看。

**Comment by RichardHou307** [comment]
重装composer后解决
