### ISSUE TITLE
新功能状态值更改

### ISSUE THREAD

**Issue by 740299743** [lxerxa/actionview#80]
请问新功能状态值如何由已完成更改为其他状态。

**Comment by lxerxa** [comment]
状态的修改是通过流程流转修改的

**Comment by 740299743** [comment]
是通过指派人员来实现流程流转呢，还是有其他途径，请指导。

**Comment by lxerxa** [comment]
就是通过操作动作流转的

**Comment by lxerxa** [comment]
流程有定义的，每一步都会关联相应的问题状态。

**Comment by RichardHou307** [comment]
新增状态后，配置工作流，添加动作，可以在满足一定条件的情况下将一个状态转至另一个状态
