### ISSUE TITLE
备注和改动纪录里显示绝对时间而不是相对时间

### ISSUE THREAD

**Issue by daiguangbao** [lxerxa/actionview#82]
现在备注和改动纪录里面，显示的每个更改的时间都是一个相对值，譬如 ‘2分钟前’、‘10天前’等等，能否配置成显示绝对时间，‘YYYY-MM-DD  HH:MM:SS'的方式？

**Comment by lxerxa** [comment]
好的，下个版本支持。

**Comment by lxerxa** [comment]
新版本已增加该功能，docker版还未发布。

**Comment by daiguangbao** [comment]
添加了这个功能之后却把备注添加按钮给去掉了

**Comment by lxerxa** [comment]
新版本丰富了权限项，其中增加了“添加备注”权限项，如果直接升级代码的话，可能需要手动的给相应的角色设置该权限，然后该按钮就显示了。

**Comment by daiguangbao** [comment]
OK了，谢谢！
