### ISSUE TITLE
后台操作日志统计功能

### ISSUE THREAD

**Issue by gjwhw** [lxerxa/actionview#83]
可否更新一个功能，是管理员可以在后台统计出项目成员登录平台的次数和各种操作的统计。

**Comment by lxerxa** [comment]
可以，这个需求已在计划中了。

**Comment by gjwhw** [comment]
感谢，还有一个关于项目权限的问题，我本是作为系统管理员，当我创建了一个应用，指定项目负责人是其他人时，我就对这个项目没有任何操作权限了，除非更换项目负责人。这个权限是本身就这么规划的么？我理解作为系统管理员是不是有最高权限？

**Comment by lxerxa** [comment]
嗯，就是这么设计的。

**Comment by gjwhw** [comment]
在工时统计的时候 有些是以w 为单位结尾的，是什么含义？
