### ISSUE TITLE
ActionView的LDAP的添加怎么配置？

### ISSUE THREAD

**Issue by miladuojx** [lxerxa/actionview#86]
现在配置出来的结果，搜索不到用户，都是0，也没有报错。有谁配置过，帮忙解答一下。谢谢！
目录名：OU=q-aaa,OU=Users,OU=bbb,DC=it,DC=abc,DC=net
主机名：ldap.abc.net
端口:389
加密:无
用户名：zhangsan
密码：******

Base DN：DC=it,DC=abc,DC=net

**Comment by lxerxa** [comment]
方便在线调试吗？

**Comment by miladuojx** [comment]
> 方便在线调试吗？

我现在估计是LDAP里面的配置，用户和用户组的信息问题，不知道你们是否有成功案例，能否粘贴个事例参考一下。谢谢！

**Comment by lxerxa** [comment]
我们就是按照你上边配置的，一直在用啊

**Comment by miladuojx** [comment]
> 我们就是按照你上边配置的，一直在用啊

我给你发邮件actionview@126.com，远程帮忙协助一下吧。谢谢！

**Comment by miladuojx** [comment]
问题已经得到解决。原因是我公司LDAP用户太多导致的。
加入搜索的规则，就可以了。
Additional User DN
OU=q-aaa,OU=Users,OU=bbb,DC=it,DC=abc,DC=net
