### ISSUE TITLE
docker镜像源还是旧的

### ISSUE THREAD

**Issue by jbcnly** [lxerxa/actionview#89]
使用dokcer方式构建，拉取镜像源的时候启动成功，发现还是旧版本1.85的，另外想请教下docker方式更新的话只能每次删除镜像再重构容器么？

**Comment by lxerxa** [comment]
没有build最新版的镜像。后台程序依赖没变的话，也可以到容器里pull代码。

**Comment by jbcnly** [comment]
好的，非常感谢~
