### ISSUE TITLE
docker方式安装，附件上传大小被限制在50M

### ISSUE THREAD

**Issue by shakermaker1984** [lxerxa/actionview#90]
修改/docker/nginx/sites-enabled里的actionview文件
将client_max_body_size值从50m改大，但容器重启后上传还是提示不能超过50m
进入容器确认此值已修改

**Comment by lxerxa** [comment]
不仅需要改nginx容器，还需要改web容器，常见问题中有说明，如下：
Q: Apache服务器用户上传较大文件失败
A: 请修改public/.htaccess配置文件中的post_max_size和upload_max_filesize。

**Comment by shakermaker1984** [comment]
也修改了web容器中public/.htaccess配置文件中的post_max_size和upload_max_filesize值，但是无效，附件上传一直提示超过50MiB

**Comment by lxerxa** [comment]
程序没有做大小的限制，能否截图看下现象？

**Comment by shakermaker1984** [comment]
![2019-12-10_092743](https://user-images.githubusercontent.com/49232760/70487320-ea81a800-1b2f-11ea-9930-4f417be923d0.jpg)
![2019-12-10_092826](https://user-images.githubusercontent.com/49232760/70487321-eb1a3e80-1b2f-11ea-94d1-37359c2d17e5.jpg)
![2019-12-10_092851](https://user-images.githubusercontent.com/49232760/70487322-eb1a3e80-1b2f-11ea-8b8d-d7f912940a1b.jpg)

**Comment by lxerxa** [comment]
改完之后先 docker-compose down，然后在up试下。

**Comment by shakermaker1984** [comment]
试过了不行，php.ini都改了也不行，你们那能试一下吗？因为很多情况需要上传大附件比如日志什么的

**Comment by lxerxa** [comment]
重启下宿主主机试试看，可能哪里有缓存。

**Comment by shakermaker1984** [comment]
重启了没效果，用centos+nginx的非docker模式安装也是一样的情况

**Comment by shakermaker1984** [comment]
检查后发现在前端issue-xxxxxxxxxx.js文件里做了限制，里面写死了50，修改后大文件下载的php代码也得改成分块下载，不然会下载失败

**Comment by lxerxa** [comment]
了解了，下个版本修复这个问题。

**Comment by lxerxa** [comment]
v1.9.3已修复该问题。
