### ISSUE TITLE
gitlab 配置 webhook

### ISSUE THREAD

**Issue by kmss-w** [lxerxa/actionview#91]
我查看了您提供的文档，没有找到更多关于配置集成的解决方案。

请问在和gitlab做集成时，如果多个项目如何配置集成呢？

**Comment by lxerxa** [comment]
ActionView 不支持同时配置多个项目，只能一个一个项目配置，后来版本专门改成这个样子的。

**Comment by pro-w-xuan** [comment]
@lxerxa 谢谢您的回复。耽误您宝贵时间。
多个项目如何配置，是文档中所示例吗？配置文件key不变添加多个吗？

**Comment by lxerxa** [comment]
更新了wiki，请参照：https://github.com/lxerxa/actionview/wiki/Integration-with-GitLab-and-GitHub。

**Comment by pro-w-xuan** [comment]
@lxerxa 🐂 ，谢谢。
