### ISSUE TITLE
能否更新下最新的docker官方镜像，感谢

### ISSUE THREAD

**Issue by stareko** [lxerxa/actionview#92]
https://hub.docker.com/r/lxerxa/actionview/tags
或是给一个国内的镜像站点，非常感谢~
目前卡在容器内配置邮件发送，我根据文档里的mail.php进行了配置，587端口也开放了
使用的是阿里云的企业邮箱，就是死活发不出去，我去哪里看日志？

**Comment by lxerxa** [comment]
最近比较忙，用dockerfile文件自己可以build的。

**Comment by lxerxa** [comment]
@stareko docker镜像已更新。

**Comment by stareko** [comment]
非常感谢~~
