### ISSUE TITLE
项目的进度和开始时间结束时间如何设置？

### ISSUE THREAD

**Issue by haydonchou** [lxerxa/actionview#96]
在甘特图中看到的任务进度都是0%，开始时间未指定？难道每次开始的时候都需要手动改一下时间与进度吗？可以不可以与状态挂钩啊，自动记录时间和进度。学习成本太高，不够自动化。

**Comment by lxerxa** [comment]
1. 新建问题时可以指定，配置界面即可。
![image](https://user-images.githubusercontent.com/5182909/76849788-0ad4a780-6881-11ea-8e66-140aabaeaf92.png)
2. 有专门针对状态的视图。
![image](https://user-images.githubusercontent.com/5182909/76849932-4f604300-6881-11ea-8741-24d8e5f96db9.png)

**Comment by haydonchou** [comment]
好吧 ，果然是需要学习。
