### ISSUE TITLE
新装的ACTIONVIEW, 用管理员不能登陆

### ISSUE THREAD

**Issue by zsdicky** [lxerxa/actionview#99]
我参考文档在CENTOS 7 安装完后, mongoDB是可以连入, actionviewDB都能打开, 主页能打开, 就是用admin@action.view/actionview 用户名和密码进不了, 是不是哪里不对?请帮助.

**Comment by zsdicky** [comment]
http://45.76.75.109/

**Comment by lxerxa** [comment]
抱歉，页面打不开。

**Comment by zsdicky** [comment]
http://pm.igo2.cc

**Comment by zsdicky** [comment]
我是新手, 请帮忙看看

**Comment by zsdicky** [comment]
今天晚试试用DOCKER, 如像是连不到数据库
